import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { DOCUMENT_GROUPS } from "../src/lib/document-groups";

const __dirname = dirname(fileURLToPath(import.meta.url));

const GROUP_TITLE_EN: Record<string, string> = {
  "İş Giriş İSG ve Oryantasyon": "Job entry, OHS and orientation",
  "İSG Kurul Kayıtları": "OHS committee records",
  "Eğitim Dosyası": "Training file",
  "Risk Değerlendirme ve Tespit Öneri": "Risk assessment and findings/recommendations",
  "Acil Durum Faaliyetleri": "Emergency preparedness",
  "Kaza, Olay ve Ramak Kala": "Incidents, events and near misses",
  "İletişim ve Yazışma": "Correspondence",
  "Talimatlar": "Instructions",
  "İSG Prosedürleri": "OHS procedures",
  "İşletme Kontrolü ve Denetim": "Workplace inspections and audits",
  "Personel Özlük ve Sözleşmeler": "Personnel files and contracts",
  "İSG Yıllık Değerlendirme": "Annual OHS review",
  "Çalışan Temsilcisi": "Worker representative",
  "İyi Uygulama": "Good practice",
  "İş Yeri Dışı Görevlendirme": "Off-site assignment",
  "Araç ve Makine Takip": "Vehicle and machinery tracking",
  "Periyodik Kontrol Belgeleri": "Periodic inspection records",
  "Diğer Kayıtlar": "Other records",
  "Yangın ve Kimyasallar": "Fire and chemicals",
  "İlkyardım Eğitimleri": "First aid training",
  "İşyeri Hekimi Dokümanları": "Occupational health physician documents",
};

const ITEM_TITLE_EN: Record<string, string> = {
  "İSG Oryantasyon Eğitim Formu": "OHS orientation training form",
  "İşe Giriş Eşleştirme Formu": "Job placement matching form",
  "İşe Giriş Sağlık Raporu Takip": "Pre-employment health report tracking",
  "İSG Taahhütnamesi": "OHS undertaking/commitment",
  "KKD Zimmet Formu": "PPE issue (custody) form",
  "İSG Bilgilendirme Tutanağı": "OHS information record",
  "Görev Tanımları": "Job descriptions",
  "Oryantasyon Kontrol Listesi": "Orientation checklist",
  "İSG Kurul Toplantı Tutanağı": "OHS committee meeting minutes",
  "Kurul Üye Listesi": "Committee member list",
  "Kurul Karar Takip Formu": "Committee decision tracking form",
  "Kurul Gündem Belgesi": "Committee agenda document",
  "Kurul Yıllık Toplantı Planı": "Annual committee meeting plan",
  "Kurul Katılım Çizelgesi": "Committee attendance chart",
  "Özel Toplantı Tutanağı": "Special meeting minutes",
  "Kurul Seçim Tutanağı": "Committee election minutes",
  "Eğitim Katılım Formu": "Training attendance form",
  "Eğitim Sertifikası": "Training certificate",
  "Yıllık Eğitim Planı": "Annual training plan",
  "Eğitim İhtiyaç Analizi": "Training needs analysis",
  "Eğitim Değerlendirme Formu": "Training evaluation form",
  "Eğitim İçerik Dokümanı": "Training content document",
  "Eğitim Etkinlik Ölçüm Formu": "Training effectiveness measurement form",
  "Eğitim Talep Formu": "Training request form",
  "Eğitim Özet Raporu": "Training summary report",
  "Risk Değerlendirme Raporu": "Risk assessment report",
  "Tespit ve Öneri Defteri": "Findings and recommendations log",
  "Tehlike ve Risk Envanteri": "Hazard and risk inventory",
  "Risk Aksiyon Planı": "Risk action plan",
  "Kaza Sonrası Risk Güncelleme": "Post-incident risk update",
  "Risk Haritası Dokümanı": "Risk map document",
  "Risk İzleme Raporu": "Risk monitoring report",
  "Risk İletişim Formu": "Risk communication form",
  "Risk Metodoloji Belgesi": "Risk methodology document",
  "Acil Durum Planı": "Emergency plan",
  "Acil Durum Ekip Listesi": "Emergency team list",
  "Tahliye Planı": "Evacuation plan",
  "Tatbikat Raporu": "Drill report",
  "Acil Durum Telefon Listesi": "Emergency phone list",
  "Acil Durum Talimatı": "Emergency instruction",
  "Toplanma Alanı Krokisi": "Assembly point sketch",
  "Acil Durum Eğitim Planı": "Emergency training plan",
  "Acil Durum Ekipman Envanteri": "Emergency equipment inventory",
  "Acil Durum Senaryoları": "Emergency scenarios",
  "İş Kazası Bildirim Formu": "Work accident notification form",
  "Kaza Araştırma Raporu": "Accident investigation report",
  "Ramak Kala Bildirim Formu": "Near-miss notification form",
  "Düzeltici Önleyici Faaliyet (DÖF) Raporu": "Corrective and preventive action (CAPA) report",
  "Kaza İstatistik Raporu": "Accident statistics report",
  "Kök Neden Analizi Raporu": "Root cause analysis report",
  "Olay Değerlendirme Tutanağı": "Incident evaluation record",
  "Resmi Yazı Şablonu": "Official letter template",
  "Uyarı Yazısı": "Warning letter",
  "Bilgilendirme Yazısı": "Information letter",
  "Genel İSG Talimatı": "General OHS instruction",
  "Makine/Ekipman Kullanım Talimatı": "Machine/equipment use instruction",
  "Kimyasal Madde Kullanım Talimatı": "Chemical substance use instruction",
  "KKD Kullanım Talimatı": "PPE use instruction",
  "İSG Politikası": "OHS policy",
  "Risk Değerlendirme Prosedürü": "Risk assessment procedure",
  "Eğitim Prosedürü": "Training procedure",
  "Acil Durum Prosedürü": "Emergency procedure",
  "Kaza Bildirimi Prosedürü": "Accident notification procedure",
  "KKD Yönetimi Prosedürü": "PPE management procedure",
  "Sağlık Gözetimi Prosedürü": "Health surveillance procedure",
  "İş İzni Prosedürü": "Permit to work procedure",
  "Yüksekte Çalışma Prosedürü": "Work at height procedure",
  "Kapalı Alan Çalışma Prosedürü": "Confined space work procedure",
  "Elektrik Güvenliği Prosedürü": "Electrical safety procedure",
  "Ergonomi Prosedürü": "Ergonomics procedure",
  "Taşeron Yönetimi Prosedürü": "Subcontractor management procedure",
  "Depolama Prosedürü": "Storage procedure",
  "İşaret ve Etiketleme Prosedürü": "Signs and labelling procedure",
  "Gece Çalışma Prosedürü": "Night work procedure",
  "Sıcak Çalışma Prosedürü": "Hot work procedure",
  "Gürültü Kontrolü Prosedürü": "Noise control procedure",
  "Toz Kontrolü Prosedürü": "Dust control procedure",
  "İş Yeri Denetim Raporu": "Workplace inspection report",
  "İç Denetim Raporu": "Internal audit report",
  "Genel Kontrol Listesi": "General inspection checklist",
  "Uygunsuzluk Raporu": "Nonconformity report",
  "İş Sözleşmesi": "Employment contract",
  "Ek Sözleşme (İSG)": "Additional contract (OHS)",
  "Gizlilik Sözleşmesi": "Confidentiality agreement",
  "Görev Tanım Belgesi": "Job description document",
  "İşe Giriş Evrak Listesi": "Pre-employment document checklist",
  "İşten Ayrılma Formu": "Termination form",
  "İzin Talep Formu": "Leave request form",
  "Fazla Mesai Talep Formu": "Overtime request form",
  "Disiplin Tutanağı": "Disciplinary record",
  "Performans Değerlendirme Formu": "Performance appraisal form",
  "Terfi Teklif Formu": "Promotion recommendation form",
  "Personel Bilgi Formu": "Personnel information form",
  "Özgeçmiş Formu": "CV form",
  "Referans Kontrol Formu": "Reference check form",
  "Bordro Mutabakat Formu": "Payroll reconciliation form",
  "Zimmet Teslim Tutanağı": "Custody handover record",
  "Yetkinlik Matrisi": "Competence matrix",
  "Yıllık Faaliyet Raporu": "Annual activity report",
  "Yıllık Çalışma Planı": "Annual work plan",
  "Çalışan Temsilcisi Seçim Tutanağı": "Worker representative election minutes",
  "Temsilci Görev Tanımı": "Representative job description",
  "Temsilci Faaliyet Raporu": "Representative activity report",
  "Temsilci Öneri Formu": "Representative suggestion form",
  "Temsilci Eğitim Kaydı": "Representative training record",
  "Temsilci Atama Yazısı": "Representative appointment letter",
  "İyi Uygulama Raporu": "Good practice report",
  "Öneri ve Ödül Sistemi Formu": "Suggestion and reward scheme form",
  "Kıyaslama (Benchmark) Raporu": "Benchmarking report",
  "Dış Görevlendirme Yazısı": "Off-site assignment letter",
  "Araç Kontrol Listesi": "Vehicle checklist",
  "Makine Bakım Formu": "Machine maintenance form",
  "Forklift Günlük Kontrol Formu": "Forklift daily inspection form",
  "Araç Zimmet Tutanağı": "Vehicle custody record",
  "Makine Envanteri": "Machine inventory",
  "Asansör Periyodik Kontrol": "Elevator periodic inspection",
  "Basınçlı Kap Kontrolü": "Pressure vessel inspection",
  "Elektrik Tesisatı Kontrolü": "Electrical installation inspection",
  "Topraklama Ölçümü": "Earthing/grounding measurement",
  "Paratoner Kontrolü": "Lightning rod inspection",
  "Yangın Tüpü Kontrolü": "Fire extinguisher inspection",
  "Yangın Dolabı Kontrolü": "Fire cabinet inspection",
  "Kompresör Kontrolü": "Compressor inspection",
  "Vinç/Kaldırma Ekipmanı Kontrolü": "Crane/lifting equipment inspection",
  "Kazan Periyodik Kontrolü": "Boiler periodic inspection",
  "Havalandırma Sistemi Kontrolü": "Ventilation system inspection",
  "Jeneratör Kontrolü": "Generator inspection",
  "LPG Tesisat Kontrolü": "LPG installation inspection",
  "Merdiven/İskele Kontrolü": "Ladder/scaffold inspection",
  "MSDS/GBF Kayıt Formu": "SDS/MSDS record form",
  "İş İzni Formu": "Permit to work form",
  "Sıcak İş İzni Formu": "Hot work permit form",
  "Yüksekte Çalışma İzni": "Work at height permit",
  "Kapalı Alan Giriş İzni": "Confined space entry permit",
  "Kazı İş İzni": "Excavation permit",
  "Ortam Ölçüm Raporu": "Environmental measurement report",
  "Gürültü Haritası": "Noise map",
  "Aydınlatma Ölçüm Raporu": "Lighting measurement report",
  "Termal Konfor Ölçümü": "Thermal comfort measurement",
  "Toz Ölçüm Raporu": "Dust measurement report",
  "Titreşim Ölçüm Raporu": "Vibration measurement report",
  "Yangın Risk Analizi": "Fire risk analysis",
  "Yangın Söndürme Planı": "Fire suppression plan",
  "Kimyasal Madde Envanteri": "Chemical inventory",
  "Kimyasal Risk Değerlendirmesi": "Chemical risk assessment",
  "Kimyasal Depolama Planı": "Chemical storage plan",
  "Yangın Tatbikat Raporu": "Fire drill report",
  "Yangın Ekipman Kontrol Çizelgesi": "Fire equipment inspection chart",
  "İlkyardım Eğitim Planı": "First aid training plan",
  "İlkyardımcı Listesi": "First aider list",
  "İlkyardım Malzeme Kontrol Formu": "First aid supplies inspection form",
  "Sağlık Gözetimi Raporu": "Health surveillance report",
  "Periyodik Muayene Planı": "Periodic medical examination plan",
  "İşe Giriş Muayene Formu": "Pre-employment medical form",
  "Meslek Hastalığı Takip Formu": "Occupational disease follow-up form",
  "İlaç ve Sarf Malzeme Takip": "Medication and consumables tracking",
  "Reçete Kayıt Formu": "Prescription log form",
  "Revir/Muayene Defteri": "Clinic/examination log",
  "Toplu Sağlık Tarama Raporu": "Mass health screening report",
  "Biyolojik Maruziyet Değerlendirmesi": "Biological exposure assessment",
  "İşyeri Hekimi Yıllık Değerlendirme": "Occupational physician annual review",
};

const groups: Record<string, { title: string; items: Record<string, string> }> = {};
for (const g of DOCUMENT_GROUPS) {
  const gt = GROUP_TITLE_EN[g.title] ?? g.title;
  const items: Record<string, string> = {};
  for (const it of g.items) {
    items[it.id] = ITEM_TITLE_EN[it.title] ?? it.title;
  }
  groups[g.key] = { title: gt, items };
}

const out = { documentCatalog: { groups } };
const dest = join(__dirname, "..", "messages", "_isg-document-catalog-en.generated.json");
writeFileSync(dest, `${JSON.stringify(out, null, 2)}\n`, "utf8");
console.log("wrote", dest);
