/**
 * ILO conventions and EU OSH directives for admin sync and RAG metadata.
 * legalWeight = international_reference — bağlayıcı TR mevzuatının altında kullanılır.
 */
export const internationalReferenceSources = [
  {
    id: "intl-ilo-c155",
    order: 1,
    sourceType: "international_convention",
    title: "ILO C155 - Occupational Safety and Health Convention, 1981",
    category: "ilo_osh",
    priority: "high",
    authority: "International Labour Organization",
    officialUrl: "https://normlex.ilo.org/dyn/nrmlx_en/f?p=NORMLEXPUB:12100:0::NO::P12100_ILO_CODE:C155",
    legalWeight: "international_reference",
    mainUse: "Ulusal İSG politikası, işveren/çalışan katılımı, önleme yaklaşımı",
    adminSyncOnly: true,
    syncIntervalDays: 90,
    ragKeyPrefix: "intl:ilo-c155",
  },
  {
    id: "intl-ilo-c187",
    order: 2,
    sourceType: "international_convention",
    title: "ILO C187 - Promotional Framework for Occupational Safety and Health Convention, 2006",
    category: "ilo_osh",
    priority: "high",
    authority: "International Labour Organization",
    officialUrl: "https://normlex.ilo.org/dyn/nrmlx_en/f?p=NORMLEXPUB:12100:0::NO::P12100_ILO_CODE:C187",
    legalWeight: "international_reference",
    mainUse: "İSG önleme kültürü, ulusal sistem, ulusal program ve sürekli iyileştirme yaklaşımı",
    adminSyncOnly: true,
    syncIntervalDays: 90,
    ragKeyPrefix: "intl:ilo-c187",
  },
  {
    id: "intl-eu-osh-framework-directive-89-391",
    order: 3,
    sourceType: "eu_directive",
    title: "Council Directive 89/391/EEC - OSH Framework Directive",
    category: "eu_osh",
    priority: "high",
    authority: "European Union / EUR-Lex",
    officialUrl: "https://eur-lex.europa.eu/eli/dir/1989/391/oj",
    legalWeight: "international_reference",
    mainUse: "AB iş sağlığı ve güvenliği çerçeve direktifi, çalışan katılımı, işveren önleme yükümlülüğü",
    adminSyncOnly: true,
    syncIntervalDays: 90,
    ragKeyPrefix: "eu:directive-89-391",
  },
  {
    id: "intl-eu-safety-signs-92-58",
    order: 4,
    sourceType: "eu_directive",
    title: "Council Directive 92/58/EEC - Safety and/or health signs at work",
    category: "eu_safety_signs",
    priority: "medium",
    authority: "European Union / EUR-Lex",
    officialUrl: "https://eur-lex.europa.eu/eli/dir/1992/58/oj",
    legalWeight: "international_reference",
    mainUse: "İşyerinde sağlık ve güvenlik işaretleri için AB minimum gerekleri",
    adminSyncOnly: true,
    syncIntervalDays: 90,
    ragKeyPrefix: "eu:directive-92-58",
  },
] as const;
export type InternationalReferenceSource = (typeof internationalReferenceSources)[number];
