/**
 * Resmî ÇSGB / İSGGM rehber, katalog ve şablon kaynakları.
 * legalWeight = guidance | reference | template — bağlayıcı mevzuatın altında kullanılır.
 */
export const officialGuideSources = [
  {
    id: "catalog-csgb-isg-yayinlari",
    order: 1,
    sourceType: "official_guide_catalog",
    title: "ÇSGB İş Sağlığı ve Güvenliği Yayınları Kataloğu",
    category: "guide_catalog",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    fallbackUrl: "https://www.csgb.gov.tr/yayinlar/raporlar/is-sagligi-ve-guvenligi/",
    mainUse:
      "ÇSGB tarafından yayımlanan tüm İSG rehber, kitap, el kitabı, sektör rehberi ve uygulama dokümanlarını keşfetmek",
    legalWeight: "reference",
    adminSyncOnly: true,
    syncIntervalDays: 7,
    discoveryMode: "crawl_catalog_and_extract_pdf_links",
    linkMatchPatterns: ["/Media/", ".pdf"],
    ragKeyPrefix: "guide-catalog:csgb-isg-yayinlari",
  },
  {
    id: "guide-kamuda-isg-rehberi",
    order: 2,
    sourceType: "official_guide",
    title: "Kamuda İş Sağlığı ve Güvenliği Rehberi",
    category: "public_sector_isg",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl: "https://www.csgb.gov.tr/Media/jt1a13o5/kamudaisgrehberi_30-01.pdf",
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    mainUse:
      "Kamu kurumlarında İSG organizasyonu, hizmet alımı, görevlendirme, risk değerlendirmesi, eğitim, kurul, bütçe ve ihale süreçleri",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 14,
    parseMode: "pdf_sections_tables_forms",
    ragKeyPrefix: "guide:kamuda-isg-rehberi",
  },
  {
    id: "guide-kamu-isg-platformu",
    order: 3,
    sourceType: "official_guide",
    title: "Kamuda İş Sağlığı ve Güvenliği / Kamu İSG Platformu Dokümanı",
    category: "public_sector_isg",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl:
      "https://www.csgb.gov.tr/Media/z1affwjv/kamuda-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi.pdf",
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    mainUse:
      "Kamu kurumlarına özel rehberler, kılavuzlar, kontrol listeleri, bilgi kartları ve kamu İSG uygulama çerçevesi",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 14,
    parseMode: "pdf_sections_tables_forms",
    ragKeyPrefix: "guide:kamu-isg-platformu",
  },
  {
    id: "guide-isg-kurullari-calisma-rehberi",
    order: 4,
    sourceType: "official_guide",
    title: "İşyerlerinde İSG Kurulları Çalışma Rehberi",
    category: "isg_board",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl:
      "https://www.csgb.gov.tr/Media/h3cgaksi/i%C5%9Fyerlerinde-isg-kurullar%C4%B1-%C3%A7al%C4%B1%C5%9Fma-rehberi_mdb.pdf",
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    mainUse:
      "İSG kurulu kurulması, kurul üyeleri, toplantı usulü, iç yönerge, tutanak, tehlike bildirim formları",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 14,
    parseMode: "pdf_sections_tables_forms",
    extractForms: true,
    ragKeyPrefix: "guide:isg-kurullari-calisma-rehberi",
  },
  {
    id: "guide-isg-uygulamalari",
    order: 5,
    sourceType: "official_guide",
    title: "İş Sağlığı ve Güvenliği Uygulamaları Rehberi",
    category: "general_isg_practice",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl:
      "https://www.csgb.gov.tr/Media/qalg3bgm/i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-guevenli%C4%9Fi-uygulamalar%C4%B1.pdf",
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    mainUse:
      "Aydınlatma, ergonomi, kimyasal risk, patlayıcı ortam, kapalı alan, kaldırma ekipmanı, ofis, iş hijyeni ve teknik İSG uygulamaları",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 14,
    parseMode: "pdf_sections_tables_checklists",
    ragKeyPrefix: "guide:isg-uygulamalari",
  },
  {
    id: "guide-yapi-islerinde-yuksekte-calisma",
    order: 6,
    sourceType: "official_guide",
    title: "Yapı İşlerinde Yüksekte Çalışmalarda İş Sağlığı ve Güvenliği Uygulama Rehberi",
    category: "construction_work_at_height",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl:
      "https://www.csgb.gov.tr/Media/s0jnggut/yap%C4%B1-i%C5%9Flerinde-y%C3%BCksekte-%C3%A7al%C4%B1%C5%9Fmalarda-isg-uygulama-rehberi.pdf",
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    mainUse:
      "Yapı işlerinde yüksekte çalışma, düşme önleme, toplu koruma, iskele, kenar koruma, çatı ve şantiye uygulamaları",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 14,
    parseMode: "pdf_sections_figures_checklists",
    ragKeyPrefix: "guide:yapi-islerinde-yuksekte-calisma",
  },
  {
    id: "guide-isveren-ve-vekili-isg-egitim",
    order: 7,
    sourceType: "official_guide",
    title: "İşveren ve İşveren Vekilinin İş Sağlığı ve Güvenliği Eğitim Rehberi",
    category: "employer_training",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl:
      "https://www.csgb.gov.tr/Media/mcjd25tt/isveren-ve-vekili-isg-egitim-rehberi_mdb.pdf",
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    mainUse: "İşveren/işveren vekili İSG farkındalığı, görev ve sorumlulukların pratik anlatımı",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    parseMode: "pdf_sections",
    ragKeyPrefix: "guide:isveren-ve-vekili-isg-egitim",
  },
  {
    id: "guide-calisma-hayatinda-ilkyardim-el-kitabi",
    order: 8,
    sourceType: "official_guide",
    title: "Çalışma Hayatında İlk Yardım El Kitabı",
    category: "first_aid",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl: null,
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    resolverTitleContains: [
      "Çalışma Hayatında İlk Yardım El Kitabı",
      "İlk Yardım El Kitabı",
    ],
    mainUse:
      "İşyerlerinde ilk yardım organizasyonu, acil müdahale bilinci ve destek elemanı eğitim içeriği",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    parseMode: "resolve_from_catalog_then_pdf_sections",
    ragKeyPrefix: "guide:calisma-hayatinda-ilkyardim",
  },
  {
    id: "guide-metal-sektoru-isg",
    order: 9,
    sourceType: "sector_guide",
    title: "Metal Sektörü İşyerlerinde İş Sağlığı ve Güvenliği Rehberi",
    category: "sector_metal",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl:
      "https://www.csgb.gov.tr/Media/nmfdclc4/metal-sekt%C3%B6r%C3%BC-i%C5%9Fyerlerinde-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi-rehberi.pdf",
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    mainUse:
      "Metal sektöründe makine, kaynak, taşlama, pres, gürültü, kimyasal ve ekipman riskleri",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    parseMode: "pdf_sections_tables_checklists",
    ragKeyPrefix: "guide:metal-sektoru-isg",
  },
  {
    id: "guide-sebze-meyve-isg",
    order: 10,
    sourceType: "sector_guide",
    title: "Sebze ve Meyve Sektörü İş Sağlığı ve Güvenliği Rehberi",
    category: "sector_food_agriculture_trade",
    priority: "medium",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl:
      "https://www.csgb.gov.tr/Media/5h5bb554/sebze-ve-meyve-rehberi-d%C3%BCzeltme.pdf",
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    mainUse:
      "Sebze-meyve işyerleri, haller, depolama, taşıma, kayma-düşme, elle taşıma, hijyen ve soğuk ortam riskleri",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    parseMode: "pdf_sections_tables_checklists",
    ragKeyPrefix: "guide:sebze-meyve-isg",
  },
  {
    id: "guide-6331-kanun-kitabi",
    order: 11,
    sourceType: "official_book",
    title: "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı",
    category: "law_explainer",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl: null,
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    resolverTitleContains: ["6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı"],
    mainUse: "6331 sayılı Kanunun açıklamalı / uygulama destekli dokümanı",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    parseMode: "resolve_from_catalog_then_pdf_sections",
    ragKeyPrefix: "book:6331-kanun-kitabi",
  },
  {
    id: "guide-6331-kanun-kitabi-en",
    order: 12,
    sourceType: "official_book",
    title: "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı - İngilizce",
    category: "law_explainer_english",
    priority: "medium",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl: null,
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    resolverTitleContains: [
      "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı (İngilizce)",
      "Occupational Health and Safety Law",
    ],
    mainUse:
      "Yabancı işveren, yabancı çalışan veya çok dilli RAG cevapları için İngilizce resmi kaynak",
    legalWeight: "guidance_translation",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    parseMode: "resolve_from_catalog_then_pdf_sections",
    ragKeyPrefix: "book:6331-kanun-kitabi-en",
  },
  {
    id: "guide-avrupa-birligi-isg",
    order: 13,
    sourceType: "official_book",
    title: "Avrupa Birliği'nde İş Sağlığı ve Güvenliği",
    category: "eu_osh_reference",
    priority: "medium",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    officialUrl: null,
    sourceCatalogUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    resolverTitleContains: [
      "Avrupa Birliği'nde İş Sağlığı ve Güvenliği",
      "Avrupa Birliği'nde İş Sağlığı ve Güvenliği",
    ],
    mainUse: "AB İSG yaklaşımı, çerçeve direktifler, karşılaştırmalı İSG politikası",
    legalWeight: "reference",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    parseMode: "resolve_from_catalog_then_pdf_sections",
    ragKeyPrefix: "book:ab-isg",
  },
  {
    id: "guide-risk-degerlendirme-rehberleri-catalog",
    order: 14,
    sourceType: "official_guide_catalog",
    title: "Risk Değerlendirmesi Rehberleri Kataloğu",
    category: "risk_assessment_guides",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı / İSGGM",
    officialUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    resolverTitleContains: [
      "Risk Değerlendirmesi Rehberi",
      "Risk Değerlendirme Rehberi",
      "Kontrol Listesi",
    ],
    mainUse:
      "Sektörel risk değerlendirmesi rehberleri, kontrol listeleri ve örnek risk analizleri",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 14,
    discoveryMode: "crawl_catalog_and_extract_matching_guides",
    ragKeyPrefix: "guide-catalog:risk-degerlendirme",
  },
  {
    id: "guide-sektor-rehberleri-catalog",
    order: 15,
    sourceType: "official_guide_catalog",
    title: "ÇSGB / İSGGM Sektörel İş Sağlığı ve Güvenliği Rehberleri Kataloğu",
    category: "sector_guides",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı / İSGGM",
    officialUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    resolverTitleContains: [
      "Sektörü İşyerlerinde İş Sağlığı ve Güvenliği Rehberi",
      "Sektöründe İş Sağlığı ve Güvenliği Rehberi",
      "İş Sağlığı ve Güvenliği Rehberi",
    ],
    mainUse:
      "Sektöre özel rehberlerin otomatik keşfi: metal, gıda, tarım, tekstil, mobilya, inşaat, hizmet, depo, lojistik vb.",
    legalWeight: "guidance",
    adminSyncOnly: true,
    syncIntervalDays: 14,
    discoveryMode: "crawl_catalog_and_extract_matching_guides",
    ragKeyPrefix: "guide-catalog:sektor-rehberleri",
  },
  {
    id: "guide-form-kontrol-listeleri-catalog",
    order: 16,
    sourceType: "official_template_catalog",
    title: "İSG Formları, Kontrol Listeleri ve Bilgi Kartları Kataloğu",
    category: "forms_checklists",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı / İSGGM",
    officialUrl:
      "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    resolverTitleContains: [
      "Kontrol Listesi",
      "Form",
      "Bilgi Kartı",
      "Talimat",
      "İç Yönerge",
      "Tutanak",
    ],
    mainUse:
      "Kurul tutanağı, tehlike bildirim formu, kontrol listesi, iç yönerge ve uygulama formları",
    legalWeight: "template",
    adminSyncOnly: true,
    syncIntervalDays: 14,
    discoveryMode: "crawl_catalog_extract_forms_and_templates",
    ragKeyPrefix: "template-catalog:isg-form-kontrol-listeleri",
  },
] as const;

export type OfficialGuideSource = (typeof officialGuideSources)[number];
