/**
 * Curated TR İSG / labour regulation catalog for admin sync and RAG metadata.
 * canonicalUrl null → resolve via mevzuat.gov.tr title lookup before sync.
 */
export const regulationSources = [
  {
    id: "reg-isg-hizmetleri",
    order: 1,
    title: "İş Sağlığı ve Güvenliği Hizmetleri Yönetmeliği",
    category: "core_isg",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=16924&MevzuatTur=7&MevzuatTertip=5",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2012/12/20121229.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-risk-degerlendirmesi",
    order: 2,
    title: "İş Sağlığı ve Güvenliği Risk Değerlendirmesi Yönetmeliği",
    category: "core_isg",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=16925&MevzuatTur=7&MevzuatTertip=5",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2012/12/20121229.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-isg-kurullari",
    order: 3,
    title: "İş Sağlığı ve Güvenliği Kurulları Hakkında Yönetmelik",
    category: "core_isg",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/01/20130118.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-is-guvenligi-uzmanlari",
    order: 4,
    title:
      "İş Güvenliği Uzmanlarının Görev, Yetki, Sorumluluk ve Eğitimleri Hakkında Yönetmelik",
    category: "core_isg_professionals",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2012/12/20121229.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-isyeri-hekimi-dsp",
    order: 5,
    title:
      "İşyeri Hekimi ve Diğer Sağlık Personelinin Görev, Yetki, Sorumluluk ve Eğitimleri Hakkında Yönetmelik",
    category: "core_isg_professionals",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/07/20130720.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-calisan-isg-egitimleri",
    order: 6,
    title: "Çalışanların İş Sağlığı ve Güvenliği Eğitimlerinin Usul ve Esasları Hakkında Yönetmelik",
    category: "core_isg_training",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/05/20130515.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-acil-durumlar",
    order: 7,
    title: "İşyerlerinde Acil Durumlar Hakkında Yönetmelik",
    category: "core_isg_emergency",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/06/20130618.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-isin-durdurulmasi",
    order: 8,
    title: "İşyerlerinde İşin Durdurulmasına Dair Yönetmelik",
    category: "core_isg_enforcement",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/03/20130330.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-isg-hizmetlerinin-desteklenmesi",
    order: 9,
    title: "İş Sağlığı ve Güvenliği Hizmetlerinin Desteklenmesi Hakkında Yönetmelik",
    category: "core_isg_support",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/12/20131224.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-is-ekipmanlari",
    order: 10,
    title: "İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği",
    category: "technical_isg",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=18318&MevzuatTur=7&MevzuatTertip=5",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/04/20130425.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-isyeri-bina-eklentileri",
    order: 11,
    title: "İşyeri Bina ve Eklentilerinde Alınacak Sağlık ve Güvenlik Önlemlerine İlişkin Yönetmelik",
    category: "technical_isg",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/07/20130717.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-kkd-isyerinde-kullanim",
    order: 12,
    title: "Kişisel Koruyucu Donanımların İşyerlerinde Kullanılması Hakkında Yönetmelik",
    category: "technical_isg",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/07/20130702.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-saglik-guvenlik-isaretleri",
    order: 13,
    title: "Sağlık ve Güvenlik İşaretleri Yönetmeliği",
    category: "technical_isg",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/09/20130911.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-ekranli-araclar",
    order: 14,
    title: "Ekranlı Araçlarla Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    category: "ergonomics",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/04/20130416.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-elle-tasima",
    order: 15,
    title: "Elle Taşıma İşleri Yönetmeliği",
    category: "ergonomics",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/07/20130724.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-gurultu",
    order: 16,
    title: "Çalışanların Gürültü ile İlgili Risklerden Korunmalarına Dair Yönetmelik",
    category: "physical_agents",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=18647&MevzuatTur=7&MevzuatTertip=5",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/07/20130728.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-titresim",
    order: 17,
    title: "Çalışanların Titreşimle İlgili Risklerden Korunmalarına Dair Yönetmelik",
    category: "physical_agents",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/08/20130822.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-tozla-mucadele",
    order: 18,
    title: "Tozla Mücadele Yönetmeliği",
    category: "physical_agents",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/11/20131105.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-kimyasal-maddeler",
    order: 19,
    title: "Kimyasal Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    category: "chemical_agents",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/08/20130812.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-kanserojen-mutajen",
    order: 20,
    title:
      "Kanserojen veya Mutajen Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    category: "chemical_agents",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/08/20130806.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-biyolojik-etkenler",
    order: 21,
    title: "Biyolojik Etkenlere Maruziyet Risklerinin Önlenmesi Hakkında Yönetmelik",
    category: "biological_agents",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/06/20130615.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-asbest",
    order: 22,
    title: "Asbestle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    category: "chemical_agents",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/01/20130125.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-patlayici-ortamlar-calisan",
    order: 23,
    title: "Patlayıcı Ortamların Tehlikelerinden Çalışanların Korunması Hakkında Yönetmelik",
    category: "explosive_atmospheres",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/04/20130430.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-is-hijyeni-lab",
    order: 24,
    title: "İş Hijyeni Ölçüm, Test ve Analiz Laboratuvarları Hakkında Yönetmelik",
    category: "industrial_hygiene",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2023/01/20230127.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-yapi-islerinde-isg",
    order: 25,
    title: "Yapı İşlerinde İş Sağlığı ve Güvenliği Yönetmeliği",
    category: "sector_construction",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/10/20131005.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-maden-isyerlerinde-isg",
    order: 26,
    title: "Maden İşyerlerinde İş Sağlığı ve Güvenliği Yönetmeliği",
    category: "sector_mining",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/09/20130919.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-balikci-gemileri",
    order: 27,
    title: "Balıkçı Gemilerinde Yapılan Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    category: "sector_marine",
    priority: "medium",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/08/20130820.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-gecici-belirli-sureli-isler",
    order: 28,
    title: "Geçici veya Belirli Süreli İşlerde İş Sağlığı ve Güvenliği Hakkında Yönetmelik",
    category: "temporary_work",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/08/20130823.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-tehlikeli-islerde-mesleki-egitim",
    order: 29,
    title:
      "Tehlikeli ve Çok Tehlikeli Sınıfta Yer Alan İşlerde Çalıştırılacakların Mesleki Eğitimlerine Dair Yönetmelik",
    category: "vocational_training",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/07/20130713.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-cocuk-genc-isciler",
    order: 30,
    title: "Çocuk ve Genç İşçilerin Çalıştırılma Usul ve Esasları Hakkında Yönetmelik",
    category: "protected_groups",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-gebe-emziren-calisanlar",
    order: 31,
    title:
      "Gebe veya Emziren Kadınların Çalıştırılma Şartlarıyla Emzirme Odaları ve Çocuk Bakım Yurtlarına Dair Yönetmelik",
    category: "protected_groups",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/08/20130816.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-kadin-gece-postalari",
    order: 32,
    title: "Kadın Çalışanların Gece Postalarında Çalıştırılma Koşulları Hakkında Yönetmelik",
    category: "protected_groups",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/07/20130724.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-postalar-halinde-calisma",
    order: 33,
    title:
      "Postalar Halinde İşçi Çalıştırılarak Yürütülen İşlerde Çalışmalara İlişkin Özel Usul ve Esaslar Hakkında Yönetmelik",
    category: "working_time",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2004/04/20040407.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-calisma-sureleri",
    order: 34,
    title: "İş Kanununa İlişkin Çalışma Süreleri Yönetmeliği",
    category: "working_time",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-fazla-calisma",
    order: 35,
    title: "Fazla Çalışma ve Fazla Sürelerle Çalışma Yönetmeliği",
    category: "working_time",
    priority: "medium",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-haftalik-is-gunlerine-bolunemeyen-calisma",
    order: 36,
    title: "Haftalık İş Günlerine Bölünemeyen Çalışma Süreleri Yönetmeliği",
    category: "working_time",
    priority: "medium",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-hazirlama-tamamlama-temizleme",
    order: 37,
    title: "Hazırlama, Tamamlama ve Temizleme İşleri Yönetmeliği",
    category: "working_time",
    priority: "medium",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2004/04/20040428.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-alt-isverenlik",
    order: 38,
    title: "Alt İşverenlik Yönetmeliği",
    category: "subcontracting",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2008/09/20080927.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-uzaktan-calisma",
    order: 39,
    title: "Uzaktan Çalışma Yönetmeliği",
    category: "remote_work",
    priority: "high",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2021/03/20210310.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-sosyal-sigorta-islemleri",
    order: 40,
    title: "Sosyal Sigorta İşlemleri Yönetmeliği",
    category: "sgk_accident_disease",
    priority: "critical",
    authority: "Sosyal Güvenlik Kurumu",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-ilkyardim",
    order: 41,
    title: "İlkyardım Yönetmeliği",
    category: "health_emergency",
    priority: "critical",
    authority: "Sağlık Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2015/07/20150729.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-hijyen-egitimi",
    order: 42,
    title: "Hijyen Eğitimi Yönetmeliği",
    category: "health_hygiene",
    priority: "high",
    authority: "Sağlık Bakanlığı / ilgili kurumlar",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/07/20130705.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-kisisel-saglik-verileri",
    order: 43,
    title: "Kişisel Sağlık Verileri Hakkında Yönetmelik",
    category: "health_data_privacy",
    priority: "high",
    authority: "Sağlık Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2019/06/20190621.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-binalarin-yangindan-korunmasi",
    order: 44,
    title: "Binaların Yangından Korunması Hakkında Yönetmelik",
    category: "fire_safety",
    priority: "critical",
    authority: "Cumhurbaşkanlığı / ilgili idareler",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2007/12/20071219.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-isyeri-acma-calisma-ruhsati",
    order: 45,
    title: "İşyeri Açma ve Çalışma Ruhsatlarına İlişkin Yönetmelik",
    category: "workplace_license",
    priority: "critical",
    authority: "İçişleri Bakanlığı / yerel idareler",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2005/08/20050810.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-yapi-denetimi-uygulama",
    order: 46,
    title: "Yapı Denetimi Uygulama Yönetmeliği",
    category: "construction_safety",
    priority: "high",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2008/02/20080205.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-planli-alanlar-imar",
    order: 47,
    title: "Planlı Alanlar İmar Yönetmeliği",
    category: "construction_safety",
    priority: "medium",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2017/07/20170703.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-santiye-sefleri",
    order: 48,
    title: "Şantiye Şefleri Hakkında Yönetmelik",
    category: "construction_safety",
    priority: "high",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-elektrik-ic-tesisleri",
    order: 49,
    title: "Elektrik İç Tesisleri Yönetmeliği",
    category: "electrical_safety",
    priority: "critical",
    authority: "Enerji ve Tabii Kaynaklar Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/arsiv/18565.pdf",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-elektrik-kuvvetli-akim",
    order: 50,
    title: "Elektrik Kuvvetli Akım Tesisleri Yönetmeliği",
    category: "electrical_safety",
    priority: "critical",
    authority: "Enerji ve Tabii Kaynaklar Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/arsiv/24246.pdf",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-elektrik-topraklama",
    order: 51,
    title: "Elektrik Tesislerinde Topraklamalar Yönetmeliği",
    category: "electrical_safety",
    priority: "critical",
    authority: "Enerji ve Tabii Kaynaklar Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/arsiv/24500.pdf",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-asansor",
    order: 52,
    title: "Asansör Yönetmeliği",
    category: "machinery_product_safety",
    priority: "high",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-asansor-bakim-periyodik-kontrol",
    order: 53,
    title: "Asansör İşletme, Bakım ve Periyodik Kontrol Yönetmeliği",
    category: "machinery_product_safety",
    priority: "critical",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-makina-emniyeti",
    order: 54,
    title: "Makina Emniyeti Yönetmeliği",
    category: "machinery_product_safety",
    priority: "critical",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-basincili-ekipmanlar",
    order: 55,
    title: "Basınçlı Ekipmanlar Yönetmeliği",
    category: "machinery_product_safety",
    priority: "critical",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-basit-basincili-kaplar",
    order: 56,
    title: "Basit Basınçlı Kaplar Yönetmeliği",
    category: "machinery_product_safety",
    priority: "high",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-tasinabilir-basincili-ekipmanlar",
    order: 57,
    title: "Taşınabilir Basınçlı Ekipmanlar Yönetmeliği",
    category: "machinery_product_safety",
    priority: "medium",
    authority: "Ulaştırma ve Altyapı Bakanlığı / Sanayi ve Teknoloji Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-atex-ekipman",
    order: 58,
    title:
      "Muhtemel Patlayıcı Ortamda Kullanılan Teçhizat ve Koruyucu Sistemler ile İlgili Yönetmelik",
    category: "explosive_atmospheres",
    priority: "critical",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-kkd-urun",
    order: 59,
    title: "Kişisel Koruyucu Donanım Yönetmeliği",
    category: "ppe_product_safety",
    priority: "high",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-yapi-malzemeleri",
    order: 60,
    title: "Yapı Malzemeleri Yönetmeliği",
    category: "construction_product_safety",
    priority: "medium",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-bekta-bekra",
    order: 61,
    title: "Büyük Endüstriyel Kazaların Önlenmesi ve Etkilerinin Azaltılması Hakkında Yönetmelik",
    category: "major_accident_prevention",
    priority: "critical",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı / AFAD",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2019/03/20190302.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-kkdik",
    order: 62,
    title: "Kimyasalların Kaydı, Değerlendirilmesi, İzni ve Kısıtlanması Hakkında Yönetmelik",
    category: "chemical_regulation",
    priority: "critical",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2017/06/20170623.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-sea",
    order: 63,
    title: "Maddelerin ve Karışımların Sınıflandırılması, Etiketlenmesi ve Ambalajlanması Hakkında Yönetmelik",
    category: "chemical_regulation",
    priority: "critical",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/12/20131211.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-guvenlik-bilgi-formlari",
    order: 64,
    title: "Zararlı Maddeler ve Karışımlara İlişkin Güvenlik Bilgi Formları Hakkında Yönetmelik",
    category: "chemical_regulation",
    priority: "critical",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2014/12/20141213.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-atik-yonetimi",
    order: 65,
    title: "Atık Yönetimi Yönetmeliği",
    category: "environment_waste",
    priority: "high",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2015/04/20150402.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-tibbi-atik",
    order: 66,
    title: "Tıbbi Atıkların Kontrolü Yönetmeliği",
    category: "environment_waste",
    priority: "high",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2017/01/20170125.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-ced",
    order: 67,
    title: "Çevresel Etki Değerlendirmesi Yönetmeliği",
    category: "environment_permit",
    priority: "medium",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2022/07/20220729.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-cevre-izin-lisans",
    order: 68,
    title: "Çevre İzin ve Lisans Yönetmeliği",
    category: "environment_permit",
    priority: "medium",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2014/09/20140910.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-tehlikeli-madde-karayolu",
    order: 69,
    title: "Tehlikeli Maddelerin Karayoluyla Taşınması Hakkında Yönetmelik",
    category: "dangerous_goods_transport",
    priority: "critical",
    authority: "Ulaştırma ve Altyapı Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-tehlikeli-madde-demiryolu",
    order: 70,
    title: "Tehlikeli Maddelerin Demiryoluyla Taşınması Hakkında Yönetmelik",
    category: "dangerous_goods_transport",
    priority: "medium",
    authority: "Ulaştırma ve Altyapı Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-tehlikeli-madde-denizyolu",
    order: 71,
    title: "Tehlikeli Maddelerin Denizyoluyla Taşınması Hakkında Yönetmelik",
    category: "dangerous_goods_transport",
    priority: "medium",
    authority: "Ulaştırma ve Altyapı Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-karayolu-tasima",
    order: 72,
    title: "Karayolu Taşıma Yönetmeliği",
    category: "transport_safety",
    priority: "medium",
    authority: "Ulaştırma ve Altyapı Bakanlığı",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2018/01/20180108.htm",
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-radyasyon-guvenligi",
    order: 73,
    title: "Radyasyon Güvenliği Yönetmeliği",
    category: "radiation_safety",
    priority: "sectoral",
    authority: "Nükleer Düzenleme Kurumu",
    canonicalUrl: null,
    officialLookupUrl: "https://www.mevzuat.gov.tr/",
    rgIssueUrl: null,
    syncMode: "admin_only_weekly",
  },
  {
    id: "reg-askeri-isyerleri-denetim",
    order: 74,
    title:
      "Askerî İşyerleri ile Yurt Güvenliği İçin Gerekli Maddeler Üretilen İşyerlerinin Denetimi, Teftişi ve Bu İşyerlerinde İşin Durdurulması Hakkında Yönetmelik",
    category: "special_workplaces",
    priority: "sectoral",
    authority: "Millî Savunma Bakanlığı / Çalışma ve Sosyal Güvenlik Bakanlığı",
    canonicalUrl:
      "https://www.mevzuat.gov.tr/anasayfa/MevzuatFihristDetayIframe?MevzuatNo=18727&MevzuatTertip=5&MevzuatTur=7",
    rgIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/08/20130816.htm",
    syncMode: "admin_only_weekly",
  },
] as const;

export type RegulationSource = (typeof regulationSources)[number];

export type RegulationCatalogPriority = RegulationSource["priority"];
