/**
 * Curated ISO / TS / IEC / CEN / TSE standards catalog for admin sync and RAG metadata.
 * Full text requires license; metadata-only indexing by default.
 */
export const standardSources = [
  {
    id: "std-ts-en-iso-45001",
    order: 1,
    sourceType: "standard",
    standardNo: "TS EN ISO 45001 / ISO 45001:2018",
    title: "İş sağlığı ve güvenliği yönetim sistemleri - Şartlar ve kullanım kılavuzu",
    category: "ohs_management_system",
    priority: "critical",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "not_binding_unless_referenced_by_law_contract_or_specification",
    isoUrl: "https://www.iso.org/iso-45001-occupational-health-and-safety.html",
    isoProductUrl: "https://www.iso.org/standard/63787.html",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "İSG yönetim sistemi, politika, liderlik, çalışan katılımı, risk-fırsat, hedef, operasyonel kontrol, performans değerlendirme, iç tetkik ve sürekli iyileştirme",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:ts-en-iso-45001"
  },
  {
    id: "std-iso-45002",
    order: 2,
    sourceType: "standard",
    standardNo: "ISO 45002",
    title: "Occupational health and safety management systems - General guidelines for the implementation of ISO 45001",
    category: "ohs_management_system_guidance",
    priority: "high",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "guidance_standard",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%2045002",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "ISO 45001 uygulama rehberi; sistem kurulumunda pratik açıklama",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-45002"
  },
  {
    id: "std-iso-45003",
    order: 3,
    sourceType: "standard",
    standardNo: "ISO 45003:2021",
    title: "Occupational health and safety management - Psychological health and safety at work - Guidelines for managing psychosocial risks",
    category: "psychosocial_risks",
    priority: "critical",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "guidance_standard",
    isoProductUrl: "https://www.iso.org/standard/64283.html",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Psikososyal riskler, iş stresi, mobbing, iş yükü, rol belirsizliği, örgütsel faktörler ve psikolojik sağlık-güvenlik yönetimi",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-45003"
  },
  {
    id: "std-iso-45004",
    order: 4,
    sourceType: "standard",
    standardNo: "ISO 45004",
    title: "Occupational health and safety management - Performance evaluation guidance",
    category: "ohs_performance_evaluation",
    priority: "high",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "guidance_standard",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%2045004",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "İSG performans göstergeleri, KPI, izleme, ölçme, değerlendirme ve iyileştirme",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-45004"
  },
  {
    id: "std-iso-31000",
    order: 5,
    sourceType: "standard",
    standardNo: "ISO 31000:2018",
    title: "Risk management - Guidelines",
    category: "risk_management",
    priority: "critical",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "guidance_standard",
    isoProductUrl: "https://www.iso.org/standard/65694.html",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Kurumsal risk yönetimi, risk değerlendirme çerçevesi, risk iştahı, risk süreçleri ve karar alma",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-31000"
  },
  {
    id: "std-iec-31010",
    order: 6,
    sourceType: "standard",
    standardNo: "IEC 31010 / ISO IEC 31010",
    title: "Risk management - Risk assessment techniques",
    category: "risk_assessment_methods",
    priority: "critical",
    authority: "IEC / ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "guidance_standard",
    isoSearchUrl: "https://www.iso.org/search.html?q=IEC%2031010",
    iecSearchUrl: "https://webstore.iec.ch/searchform&q=31010",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Fine-Kinney, FMEA, HAZOP, Bow-Tie, What-if, LOPA gibi risk değerlendirme teknikleri için metodolojik kaynak",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iec-31010"
  },
  {
    id: "std-iso-19011",
    order: 7,
    sourceType: "standard",
    standardNo: "ISO 19011:2018",
    title: "Guidelines for auditing management systems",
    category: "audit",
    priority: "high",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "guidance_standard",
    isoProductUrl: "https://www.iso.org/standard/70017.html",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "İç tetkik, denetim programı, denetçi yeterliliği ve yönetim sistemi denetim metodolojisi",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-19011"
  },
  {
    id: "std-iso-14001",
    order: 8,
    sourceType: "standard",
    standardNo: "ISO 14001:2015",
    title: "Environmental management systems - Requirements with guidance for use",
    category: "environment_management",
    priority: "high",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "voluntary_standard",
    isoProductUrl: "https://www.iso.org/standard/60857.html",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Çevre yönetim sistemi, kimyasal, atık, acil durum ve çevre-İSG kesişimi",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-14001"
  },
  {
    id: "std-iso-9001",
    order: 9,
    sourceType: "standard",
    standardNo: "ISO 9001:2015",
    title: "Quality management systems - Requirements",
    category: "quality_management",
    priority: "medium",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "voluntary_standard",
    isoProductUrl: "https://www.iso.org/standard/62085.html",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Dokümantasyon, proses yaklaşımı, uygunsuzluk, düzeltici faaliyet ve yönetim sistemi entegrasyonu",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-9001"
  },
  {
    id: "std-iso-50001",
    order: 10,
    sourceType: "standard",
    standardNo: "ISO 50001:2018",
    title: "Energy management systems - Requirements with guidance for use",
    category: "energy_management",
    priority: "medium",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "voluntary_standard",
    isoProductUrl: "https://www.iso.org/standard/69426.html",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Enerji yönetimi, enerji tesisleri, enerji verimliliği ve işletme güvenliğiyle dolaylı bağlantı",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-50001"
  },
  {
    id: "std-iso-22301",
    order: 11,
    sourceType: "standard",
    standardNo: "ISO 22301",
    title: "Security and resilience - Business continuity management systems",
    category: "business_continuity_emergency",
    priority: "medium",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "voluntary_standard",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%2022301",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "İş sürekliliği, afet, acil durum ve kritik faaliyetlerin sürdürülmesi",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-22301"
  },
  {
    id: "std-iso-27001",
    order: 12,
    sourceType: "standard",
    standardNo: "ISO/IEC 27001",
    title: "Information security management systems",
    category: "information_security_health_data",
    priority: "medium",
    authority: "ISO / IEC / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "voluntary_standard",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%2FIEC%2027001",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Çalışan sağlık verileri, İSG kayıtları, KVKK, RAG sistem güvenliği ve belge erişim kontrolü",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-iec-27001"
  },

  {
    id: "std-iso-12100",
    order: 13,
    sourceType: "standard",
    standardNo: "TS EN ISO 12100 / ISO 12100",
    title: "Makina emniyeti - Tasarım için genel prensipler - Risk değerlendirmesi ve risk azaltma",
    category: "machine_safety",
    priority: "critical",
    authority: "ISO / CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_machinery_safety",
    isoProductUrl: "https://www.iso.org/standard/51528.html",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Makine risk değerlendirmesi, risk azaltma, tasarımdan güvenlik",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-12100"
  },
  {
    id: "std-iso-13849-1",
    order: 14,
    sourceType: "standard",
    standardNo: "TS EN ISO 13849-1 / ISO 13849-1",
    title: "Makinalarda güvenlik - Kumanda sistemlerinin güvenlikle ilgili parçaları",
    category: "machine_safety_control_systems",
    priority: "critical",
    authority: "ISO / CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_machinery_safety",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%2013849-1",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Makine emniyet devreleri, performans seviyesi, kontrol sistemi güvenliği",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-13849-1"
  },
  {
    id: "std-iso-13850",
    order: 15,
    sourceType: "standard",
    standardNo: "TS EN ISO 13850 / ISO 13850",
    title: "Makinalarda güvenlik - Acil durdurma fonksiyonu",
    category: "machine_safety_emergency_stop",
    priority: "high",
    authority: "ISO / CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_machinery_safety",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%2013850",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Acil stop, makine güvenliği ve kontrol tedbirleri",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-13850"
  },
  {
    id: "std-iec-60204-1",
    order: 16,
    sourceType: "standard",
    standardNo: "TS EN IEC 60204-1 / IEC 60204-1",
    title: "Makinalarda güvenlik - Makinaların elektrik donanımı",
    category: "machine_electrical_safety",
    priority: "critical",
    authority: "IEC / CENELEC / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_machine_electrical_safety",
    iecSearchUrl: "https://webstore.iec.ch/searchform&q=60204-1",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Makine elektrik donanımı, elektrik güvenliği, acil durdurma, kontrol panosu, koruma devreleri",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iec-60204-1"
  },
  {
    id: "std-iec-60364",
    order: 17,
    sourceType: "standard",
    standardNo: "TS HD / IEC 60364 serisi",
    title: "Alçak gerilim elektrik tesisleri",
    category: "electrical_installation_safety",
    priority: "critical",
    authority: "IEC / CENELEC / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_electrical_installations",
    iecSearchUrl: "https://webstore.iec.ch/searchform&q=60364",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Elektrik tesisatı, koruma, topraklama, kaçak akım, devre güvenliği ve periyodik kontrol bağlantısı",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iec-60364-series"
  },
  {
    id: "std-iec-60079",
    order: 18,
    sourceType: "standard",
    standardNo: "TS EN IEC 60079 serisi",
    title: "Patlayıcı ortamlar - ATEX / Ex ekipman ve tesisat standartları",
    category: "atex_explosive_atmospheres",
    priority: "critical",
    authority: "IEC / CENELEC / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_explosive_atmospheres",
    iecSearchUrl: "https://webstore.iec.ch/searchform&q=60079",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Patlayıcı ortam sınıflandırması, Ex ekipman, bakım, muayene, zonlar, elektrik tesisatı",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iec-60079-series"
  },
  {
    id: "std-iso-7010",
    order: 19,
    sourceType: "standard",
    standardNo: "TS EN ISO 7010 / ISO 7010",
    title: "Grafik semboller - Güvenlik renkleri ve güvenlik işaretleri - Kayıtlı güvenlik işaretleri",
    category: "safety_signs",
    priority: "high",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_safety_signs",
    isoProductUrl: "https://www.iso.org/standard/72424.html",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "İşyerinde yasak, uyarı, emredici, acil çıkış, yangın ve ilk yardım işaretleri",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-7010"
  },
  {
    id: "std-iso-3864",
    order: 20,
    sourceType: "standard",
    standardNo: "ISO 3864 serisi",
    title: "Graphical symbols - Safety colours and safety signs",
    category: "safety_signs_design",
    priority: "medium",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_safety_signs",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%203864",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Güvenlik işaretlerinin renk, tasarım ve sembol prensipleri",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-3864-series"
  },
  {
    id: "std-en-12464-1",
    order: 21,
    sourceType: "standard",
    standardNo: "TS EN 12464-1",
    title: "Işık ve aydınlatma - Çalışma yerlerinin aydınlatılması - İç çalışma yerleri",
    category: "lighting",
    priority: "high",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_workplace_lighting",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Ofis, üretim alanı, depo, hastane, okul gibi iç çalışma alanlarında aydınlatma gereksinimleri",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-12464-1"
  },
  {
    id: "std-en-1838",
    order: 22,
    sourceType: "standard",
    standardNo: "TS EN 1838",
    title: "Aydınlatma uygulamaları - Acil aydınlatma",
    category: "emergency_lighting",
    priority: "high",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_emergency_lighting",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Acil çıkış, kaçış yolu, panik önleme ve acil durum aydınlatması",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-1838"
  },
  {
    id: "std-en-689",
    order: 23,
    sourceType: "standard",
    standardNo: "TS EN 689",
    title: "Workplace exposure - Measurement of exposure by inhalation to chemical agents",
    category: "industrial_hygiene_chemical_exposure",
    priority: "critical",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_workplace_exposure_measurement",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Kimyasal maruziyet ölçümü, iş hijyeni değerlendirmesi, ölçüm stratejisi ve sınır değer karşılaştırması",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-689"
  },
  {
    id: "std-en-482",
    order: 24,
    sourceType: "standard",
    standardNo: "TS EN 482",
    title: "Workplace exposure - Procedures for the determination of the concentration of chemical agents",
    category: "industrial_hygiene_measurement_quality",
    priority: "high",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_workplace_exposure_measurement",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "İş hijyeni ölçüm metotlarının performans gereklilikleri",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-482"
  },
  {
    id: "std-iso-9612",
    order: 25,
    sourceType: "standard",
    standardNo: "ISO 9612",
    title: "Acoustics - Determination of occupational noise exposure - Engineering method",
    category: "noise_exposure",
    priority: "high",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_noise_measurement",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%209612",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Çalışan gürültü maruziyeti ölçümü ve değerlendirmesi",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-9612"
  },
  {
    id: "std-iso-5349",
    order: 26,
    sourceType: "standard",
    standardNo: "ISO 5349 serisi",
    title: "Mechanical vibration - Measurement and evaluation of human exposure to hand-transmitted vibration",
    category: "vibration_exposure",
    priority: "high",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_vibration_measurement",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%205349",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "El-kol titreşimi ölçümü ve maruziyet değerlendirmesi",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-5349-series"
  },
  {
    id: "std-iso-11228",
    order: 27,
    sourceType: "standard",
    standardNo: "ISO 11228 serisi",
    title: "Ergonomics - Manual handling",
    category: "ergonomics_manual_handling",
    priority: "high",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_ergonomics",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%2011228",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Elle taşıma, itme-çekme, tekrarlı taşıma ve ergonomik risk değerlendirmesi",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-11228-series"
  },
  {
    id: "std-iso-9241",
    order: 28,
    sourceType: "standard",
    standardNo: "ISO 9241 serisi",
    title: "Ergonomics of human-system interaction",
    category: "ergonomics_display_screen_work",
    priority: "medium",
    authority: "ISO / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_screen_work_and_ergonomics",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%209241",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Ekranlı araçlar, kullanıcı arayüzü, ofis ergonomisi ve insan-sistem etkileşimi",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-9241-series"
  },
  {
    id: "std-en-361",
    order: 29,
    sourceType: "standard",
    standardNo: "TS EN 361",
    title: "Kişisel koruyucu donanım - Yüksekten düşmeye karşı - Tam vücut kemerleri",
    category: "work_at_height_ppe",
    priority: "critical",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_fall_protection_ppe",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Yüksekte çalışma tam vücut emniyet kemeri uygunluğu",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-361"
  },
  {
    id: "std-en-363",
    order: 30,
    sourceType: "standard",
    standardNo: "TS EN 363",
    title: "Kişisel düşmeye karşı koruyucu sistemler",
    category: "work_at_height_ppe",
    priority: "critical",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_fall_protection_systems",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Düşüş durdurma, konumlandırma, kısıtlama ve kurtarma sistemleri",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-363"
  },
  {
    id: "std-en-795",
    order: 31,
    sourceType: "standard",
    standardNo: "TS EN 795",
    title: "Düşmeye karşı koruyucu donanım - Ankraj cihazları",
    category: "work_at_height_anchor",
    priority: "critical",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_anchor_devices",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Ankraj noktaları, yaşam hattı ve yüksekten düşmeye karşı bağlantı ekipmanları",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-795"
  },
  {
    id: "std-en-12811",
    order: 32,
    sourceType: "standard",
    standardNo: "TS EN 12811 serisi",
    title: "Geçici iş donanımları - İskeleler",
    category: "scaffolding",
    priority: "critical",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_scaffolding",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "İskele tasarımı, kullanım, yük sınıfı, platform, korkuluk ve geçici iş ekipmanı",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-12811-series"
  },
  {
    id: "std-en-397",
    order: 33,
    sourceType: "standard",
    standardNo: "TS EN 397",
    title: "Endüstriyel emniyet baretleri",
    category: "ppe_head_protection",
    priority: "high",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_ppe",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Baret seçimi ve ürün uygunluğu",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-397"
  },
  {
    id: "std-en-166",
    order: 34,
    sourceType: "standard",
    standardNo: "TS EN 166",
    title: "Kişisel göz koruması",
    category: "ppe_eye_protection",
    priority: "high",
    authority: "CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_ppe",
    cenSearchUrl: "https://standards.cencenelec.eu/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Gözlük, yüz siperi, mekanik/kimyasal/sıçrama risklerine karşı göz koruması",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:en-166"
  },
  {
    id: "std-iso-20345",
    order: 35,
    sourceType: "standard",
    standardNo: "TS EN ISO 20345 / ISO 20345",
    title: "Kişisel koruyucu donanım - Güvenlik ayakkabıları",
    category: "ppe_foot_protection",
    priority: "high",
    authority: "ISO / CEN / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_ppe",
    isoSearchUrl: "https://www.iso.org/search.html?q=ISO%2020345",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Güvenlik ayakkabısı sınıfları, burun koruma, taban, kaymazlık, delinme direnci",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-20345"
  },
  {
    id: "std-iso-iec-17025",
    order: 36,
    sourceType: "standard",
    standardNo: "TS EN ISO/IEC 17025 / ISO/IEC 17025",
    title: "Deney ve kalibrasyon laboratuvarlarının yeterliliği için genel şartlar",
    category: "laboratory_accreditation",
    priority: "critical",
    authority: "ISO / IEC / TÜRKAK / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_accredited_measurements",
    isoProductUrl: "https://www.iso.org/standard/66912.html",
    turkakUrl: "https://www.turkak.org.tr/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "İş hijyeni ölçümleri, kalibrasyon, laboratuvar yetkinliği ve akredite analiz sonuçları",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-iec-17025"
  },
  {
    id: "std-iso-iec-17020",
    order: 37,
    sourceType: "standard",
    standardNo: "TS EN ISO/IEC 17020 / ISO/IEC 17020",
    title: "Muayene kuruluşlarının çalışması için şartlar",
    category: "inspection_body_accreditation",
    priority: "critical",
    authority: "ISO / IEC / TÜRKAK / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_inspection_bodies",
    isoProductUrl: "https://www.iso.org/standard/52994.html",
    turkakUrl: "https://www.turkak.org.tr/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "Periyodik kontrol, muayene kuruluşu yeterliliği, bağımsızlık ve teknik yetkinlik",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-iec-17020"
  },
  {
    id: "std-iso-iec-17021-1",
    order: 38,
    sourceType: "standard",
    standardNo: "ISO/IEC 17021-1",
    title: "Management system certification bodies - Requirements",
    category: "certification_body_accreditation",
    priority: "medium",
    authority: "ISO / IEC / TÜRKAK / TSE",
    legalWeight: "technical_reference",
    bindingStatus: "technical_reference_for_certification_bodies",
    isoProductUrl: "https://www.iso.org/standard/61651.html",
    turkakUrl: "https://www.turkak.org.tr/",
    tseSearchUrl: "https://intweb.tse.org.tr/Standard/Standard/StandardAra.aspx",
    mainUse: "ISO 45001 belgelendirme kuruluşlarının yeterliliği",
    licenseMode: "metadata_only_unless_licensed",
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "standard:iso-iec-17021-1"
  }
] as const;
export type StandardSource = (typeof standardSources)[number];
