/**
 * Curated TR tebliğ, uyumlaştırılmış standart tebliği ve yıllık tablo kaynakları.
 * canonicalUrl yoksa mevzuat.gov.tr başlık çözümü + RG fallback (catalog_metadata).
 */
export const tebligAndTableSources = [
  {
    id: "teblig-isyeri-tehlike-siniflari",
    order: 1,
    sourceType: "communique",
    title: "İş Sağlığı ve Güvenliğine İlişkin İşyeri Tehlike Sınıfları Tebliği",
    category: "core_isg_tehlike_sinifi",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    mainUse: "NACE kodu / işyeri tehlike sınıfı / az tehlikeli-tehlikeli-çok tehlikeli ayrımı",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    mevzuatTur: 9,
    mevzuatTertip: 5,
    resmiGazeteIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2012/12/20121226.htm",
    resmiGazeteIssueNo: "28509",
    firstPublicationDate: "2012-12-26",
    changeResolverTitleContains: [
      "İş Sağlığı ve Güvenliğine İlişkin İşyeri Tehlike Sınıfları Tebliğinde Değişiklik Yapılmasına Dair Tebliğ",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 7,
    ragKeyPrefix: "communique:isyeri-tehlike-siniflari",
  },
  {
    id: "teblig-is-ekipmanlari-periyodik-kontrol-yetkili-kisi",
    order: 2,
    sourceType: "communique",
    title:
      "İş Ekipmanlarının Periyodik Kontrollerini Yapmaya Yetkili Kişilerin Kayıt ve Eğitimlerine İlişkin Tebliğ",
    category: "core_isg_periyodik_kontrol",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    mainUse: "Periyodik kontrol yapacak kişilerin kayıt, eğitim, yetki ve belge süreçleri",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    mevzuatTur: 9,
    mevzuatTertip: 5,
    resmiGazeteIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2017/10/20171001.htm",
    resmiGazeteIssueNo: "30197",
    firstPublicationDate: "2017-10-01",
    changeResolverTitleContains: [
      "İş Ekipmanlarının Periyodik Kontrollerini Yapmaya Yetkili Kişilerin Kayıt ve Eğitimlerine İlişkin Tebliğde Değişiklik Yapılmasına Dair Tebliğ",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 7,
    ragKeyPrefix: "communique:is-ekipmanlari-periyodik-kontrol-yetkili-kisi",
  },
  {
    id: "teblig-asbest-sokumu-egitim-programlari",
    order: 3,
    sourceType: "communique",
    title: "Asbest Sökümü ile İlgili Eğitim Programlarına İlişkin Tebliğ",
    category: "core_isg_asbest",
    priority: "critical",
    authority: "Çalışma ve Sosyal Güvenlik Bakanlığı",
    mainUse: "Asbest söküm uzmanı ve asbest söküm çalışanı eğitim programları",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    mevzuatTur: 9,
    mevzuatTertip: 5,
    resmiGazeteIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2013/06/20130629.htm",
    resmiGazeteIssueNo: "28692",
    firstPublicationDate: "2013-06-29",
    changeResolverTitleContains: [
      "Asbest Sökümü ile İlgili Eğitim Programlarına İlişkin Tebliğde Değişiklik Yapılmasına Dair Tebliğ",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 7,
    ragKeyPrefix: "communique:asbest-sokumu-egitim-programlari",
  },
  {
    id: "table-6331-idari-para-cezalari",
    order: 4,
    sourceType: "annual_table",
    title: "6331 Sayılı İş Sağlığı ve Güvenliği Kanununa Göre Uygulanacak İdari Para Cezaları",
    category: "core_isg_idari_para_cezalari",
    priority: "critical",
    authority: "İş Sağlığı ve Güvenliği Genel Müdürlüğü",
    mainUse: "6331 kapsamındaki ihlallerin yıllık idari para cezası tutarları",
    officialUrl:
      "https://www.csgb.gov.tr/isggm/tr/%C4%B1sg-hizmetleri/idari-para-cezalari/",
    expectedDocumentPattern: [
      "6331 SAYILI İŞ SAĞLIĞI VE GÜVENLİĞİ KANUNUNA GÖRE 2026 YILINDA UYGULANACAK İDARİ PARA CEZALARI",
      "6331 SAYILI İŞ SAĞLIĞI VE GÜVENLİĞİ KANUNUNA GÖRE 2025 YILINDA UYGULANACAK İDARİ PARA CEZALARI",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 7,
    ragKeyPrefix: "table:6331-idari-para-cezalari",
  },
  {
    id: "teblig-vuk-yeniden-degerleme-orani",
    order: 5,
    sourceType: "annual_communique",
    title: "Vergi Usul Kanunu Genel Tebliği - Yeniden Değerleme Oranı",
    category: "idari_para_cezasi_hesaplama",
    priority: "high",
    authority: "Hazine ve Maliye Bakanlığı / Gelir İdaresi Başkanlığı",
    mainUse: "6331 idari para cezalarının yıllık yeniden değerleme hesabı için oran kaynağı",
    officialLookupUrl: "https://www.gib.gov.tr/",
    resmiGazeteLookupUrl: "https://www.resmigazete.gov.tr/",
    resolverTitleContains: ["Vergi Usul Kanunu Genel Tebliği", "Yeniden Değerleme Oranı"],
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "communique:vuk-yeniden-degerleme-orani",
  },
  {
    id: "teblig-tmgd",
    order: 6,
    sourceType: "communique",
    title: "Tehlikeli Madde Güvenlik Danışmanlığı Hakkında Tebliğ",
    category: "dangerous_goods_transport",
    priority: "high",
    authority: "Ulaştırma ve Altyapı Bakanlığı",
    mainUse: "Tehlikeli madde taşımacılığı yapan işletmelerde TMGD yükümlülüğü",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    mevzuatTur: 9,
    mevzuatTertip: 5,
    resmiGazeteIssueUrl: "https://www.resmigazete.gov.tr/eskiler/2014/05/20140522.htm",
    firstPublicationDate: "2014-05-22",
    changeResolverTitleContains: ["Tehlikeli Madde Güvenlik Danışmanlığı Hakkında Tebliğde Değişiklik"],
    adminSyncOnly: true,
    syncIntervalDays: 14,
    ragKeyPrefix: "communique:tmgd",
  },
  {
    id: "teblig-bekra-guvenlik-raporu",
    order: 7,
    sourceType: "communique",
    title: "Büyük Endüstriyel Kazalarla İlgili Güvenlik Raporu Tebliği",
    category: "major_accident_prevention",
    priority: "sectoral_critical",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    mainUse: "BEKRA kapsamındaki üst seviyeli kuruluşlarda güvenlik raporu içeriği",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    resmiGazeteLookupUrl: "https://www.resmigazete.gov.tr/",
    resolverTitleContains: ["Büyük Endüstriyel Kazalarla İlgili Güvenlik Raporu Tebliği"],
    adminSyncOnly: true,
    syncIntervalDays: 14,
    ragKeyPrefix: "communique:bekra-guvenlik-raporu",
  },
  {
    id: "teblig-bekra-dahili-acil-durum-plani",
    order: 8,
    sourceType: "communique",
    title: "Büyük Endüstriyel Kazalarla İlgili Dahili Acil Durum Planı Tebliği",
    category: "major_accident_prevention",
    priority: "sectoral_critical",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı / AFAD",
    mainUse: "BEKRA kapsamındaki kuruluşlarda dahili acil durum planı içeriği",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    resmiGazeteLookupUrl: "https://www.resmigazete.gov.tr/",
    resolverTitleContains: ["Büyük Endüstriyel Kazalarla İlgili Dahili Acil Durum Planı Tebliği"],
    adminSyncOnly: true,
    syncIntervalDays: 14,
    ragKeyPrefix: "communique:bekra-dahili-acil-durum-plani",
  },
  {
    id: "teblig-kimyasallar-sds-guvenlik-bilgi-formu",
    order: 9,
    sourceType: "communique_or_regulation_related",
    title:
      "Güvenlik Bilgi Formları ve kimyasal güvenlik bilgi formu yükümlülüklerine ilişkin tebliğ/değişiklik kaynakları",
    category: "chemical_sds",
    priority: "high",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    mainUse: "SDS/GBF, zararlı madde ve karışımlar, kimyasal risk değerlendirmesi",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    resmiGazeteLookupUrl: "https://www.resmigazete.gov.tr/",
    resolverTitleContains: [
      "Güvenlik Bilgi Formları",
      "Zararlı Maddeler ve Karışımlara İlişkin Güvenlik Bilgi Formları",
      "Kimyasalların Kaydı, Değerlendirilmesi, İzni ve Kısıtlanması",
      "Maddelerin ve Karışımların Sınıflandırılması, Etiketlenmesi ve Ambalajlanması",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 14,
    ragKeyPrefix: "communique:chemical-sds",
  },
  {
    id: "teblig-makina-uyumlastirilmis-standartlar",
    order: 10,
    sourceType: "harmonized_standards_communique",
    title: "Makina Emniyeti Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    category: "machinery_safety",
    priority: "high",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    mainUse: "Makine emniyeti, CE, uygunluk değerlendirmesi ve teknik standart bağlantısı",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    resmiGazeteLookupUrl: "https://www.resmigazete.gov.tr/",
    resolverTitleContains: [
      "Makina Emniyeti Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar",
      "Makine Emniyeti Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "communique:makina-uyumlastirilmis-standartlar",
  },
  {
    id: "teblig-kkd-uyumlastirilmis-standartlar",
    order: 11,
    sourceType: "harmonized_standards_communique",
    title:
      "Kişisel Koruyucu Donanım Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    category: "ppe_product_safety",
    priority: "high",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    mainUse: "KKD uygunluk, CE, standart ve ürün güvenliği bağlantısı",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    resmiGazeteLookupUrl: "https://www.resmigazete.gov.tr/",
    resolverTitleContains: [
      "Kişisel Koruyucu Donanım Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar",
      "Kişisel Koruyucu Donanım Yönetmeliği Kapsamında Uyumlaştırılmış Ulusal Standartlar",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "communique:kkd-uyumlastirilmis-standartlar",
  },
  {
    id: "teblig-basincili-ekipman-uyumlastirilmis-standartlar",
    order: 12,
    sourceType: "harmonized_standards_communique",
    title: "Basınçlı Ekipmanlar Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    category: "pressure_equipment_safety",
    priority: "high",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    mainUse: "Basınçlı kap, kazan, tank, kompresör ve basınçlı sistem uygunluğu",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    resmiGazeteLookupUrl: "https://www.resmigazete.gov.tr/",
    resolverTitleContains: [
      "Basınçlı Ekipmanlar Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "communique:basincili-ekipman-uyumlastirilmis-standartlar",
  },
  {
    id: "teblig-atex-uyumlastirilmis-standartlar",
    order: 13,
    sourceType: "harmonized_standards_communique",
    title:
      "Muhtemel Patlayıcı Ortamda Kullanılan Teçhizat ve Koruyucu Sistemler ile İlgili Yönetmelik Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    category: "atex_equipment_safety",
    priority: "sectoral_critical",
    authority: "Sanayi ve Teknoloji Bakanlığı",
    mainUse: "ATEX ekipman, patlayıcı ortam, CE ve uygunluk değerlendirmesi",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    resmiGazeteLookupUrl: "https://www.resmigazete.gov.tr/",
    resolverTitleContains: [
      "Muhtemel Patlayıcı Ortamda Kullanılan Teçhizat",
      "Koruyucu Sistemler",
      "Uyumlaştırılmış Standartlar",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "communique:atex-uyumlastirilmis-standartlar",
  },
  {
    id: "teblig-yapi-malzemeleri-uyumlastirilmis-standartlar",
    order: 14,
    sourceType: "harmonized_standards_communique",
    title: "Yapı Malzemeleri Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    category: "construction_product_safety",
    priority: "medium",
    authority: "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    mainUse: "Yapı malzemeleri, şantiye ve yapı güvenliğiyle bağlantılı ürün standardı kaynakları",
    mevzuatLookupUrl: "https://www.mevzuat.gov.tr/",
    resmiGazeteLookupUrl: "https://www.resmigazete.gov.tr/",
    resolverTitleContains: [
      "Yapı Malzemeleri Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar",
    ],
    adminSyncOnly: true,
    syncIntervalDays: 30,
    ragKeyPrefix: "communique:yapi-malzemeleri-uyumlastirilmis-standartlar",
  },
] as const;

export type TebligAndTableSource = (typeof tebligAndTableSources)[number];
