BEGIN;

INSERT INTO public.legal_documents (
  doc_type,
  doc_number,
  title,
  source_url,
  corpus_scope,
  jurisdiction_code,
  is_active,
  catalog_metadata
)
SELECT
  r.doc_type::text,
  r.doc_number::text,
  r.title::text,
  r.source_url::text,
  'official'::text,
  'GLOBAL'::text,
  true,
  jsonb_strip_nulls(jsonb_build_object(
      'catalog_id', r.id,
      'catalog_order', r."order",
      'source_type', r.source_type,
      'category', r.category,
      'priority', r.priority,
      'authority', r.authority,
      'main_use', r.main_use,
      'legal_weight', r.legal_weight,
      'retrieval_rank_key', r.retrieval_rank_key,
      'corpus_role', 'international_reference',
      'binding_override', false,
      'rag_key_prefix', r.rag_key_prefix,
      'admin_sync_only', r.admin_sync_only,
      'sync_interval_days', r.sync_interval_days,
      'last_status', r.last_status
    ))
FROM jsonb_to_recordset($catalog$[
  {
    "id": "intl-ilo-c155",
    "order": 1,
    "doc_type": "announcement",
    "source_type": "international_convention",
    "title": "ILO C155 - Occupational Safety and Health Convention, 1981",
    "doc_number": "intl-ilo-c155",
    "category": "ilo_osh",
    "priority": "high",
    "authority": "International Labour Organization",
    "main_use": "Ulusal İSG politikası, işveren/çalışan katılımı, önleme yaklaşımı",
    "legal_weight": "international_reference",
    "retrieval_rank_key": "ilo_convention",
    "source_url": "https://normlex.ilo.org/dyn/nrmlx_en/f?p=NORMLEXPUB:12100:0::NO::P12100_ILO_CODE:C155",
    "rag_key_prefix": "intl:ilo-c155",
    "sync_interval_days": 90,
    "admin_sync_only": true,
    "last_status": "metadata_only"
  },
  {
    "id": "intl-ilo-c187",
    "order": 2,
    "doc_type": "announcement",
    "source_type": "international_convention",
    "title": "ILO C187 - Promotional Framework for Occupational Safety and Health Convention, 2006",
    "doc_number": "intl-ilo-c187",
    "category": "ilo_osh",
    "priority": "high",
    "authority": "International Labour Organization",
    "main_use": "İSG önleme kültürü, ulusal sistem, ulusal program ve sürekli iyileştirme yaklaşımı",
    "legal_weight": "international_reference",
    "retrieval_rank_key": "ilo_convention",
    "source_url": "https://normlex.ilo.org/dyn/nrmlx_en/f?p=NORMLEXPUB:12100:0::NO::P12100_ILO_CODE:C187",
    "rag_key_prefix": "intl:ilo-c187",
    "sync_interval_days": 90,
    "admin_sync_only": true,
    "last_status": "metadata_only"
  },
  {
    "id": "intl-eu-osh-framework-directive-89-391",
    "order": 3,
    "doc_type": "announcement",
    "source_type": "eu_directive",
    "title": "Council Directive 89/391/EEC - OSH Framework Directive",
    "doc_number": "intl-eu-osh-framework-directive-89-391",
    "category": "eu_osh",
    "priority": "high",
    "authority": "European Union / EUR-Lex",
    "main_use": "AB iş sağlığı ve güvenliği çerçeve direktifi, çalışan katılımı, işveren önleme yükümlülüğü",
    "legal_weight": "international_reference",
    "retrieval_rank_key": "eu_directive",
    "source_url": "https://eur-lex.europa.eu/eli/dir/1989/391/oj",
    "rag_key_prefix": "eu:directive-89-391",
    "sync_interval_days": 90,
    "admin_sync_only": true,
    "last_status": "metadata_only"
  },
  {
    "id": "intl-eu-safety-signs-92-58",
    "order": 4,
    "doc_type": "announcement",
    "source_type": "eu_directive",
    "title": "Council Directive 92/58/EEC - Safety and/or health signs at work",
    "doc_number": "intl-eu-safety-signs-92-58",
    "category": "eu_safety_signs",
    "priority": "medium",
    "authority": "European Union / EUR-Lex",
    "main_use": "İşyerinde sağlık ve güvenlik işaretleri için AB minimum gerekleri",
    "legal_weight": "international_reference",
    "retrieval_rank_key": "eu_directive",
    "source_url": "https://eur-lex.europa.eu/eli/dir/1992/58/oj",
    "rag_key_prefix": "eu:directive-92-58",
    "sync_interval_days": 90,
    "admin_sync_only": true,
    "last_status": "metadata_only"
  }
]$catalog$::jsonb) AS r(
  id text,
  "order" int,
  doc_type text,
  source_type text,
  title text,
  doc_number text,
  category text,
  priority text,
  authority text,
  main_use text,
  legal_weight text,
  retrieval_rank_key text,
  source_url text,
  rag_key_prefix text,
  sync_interval_days int,
  admin_sync_only boolean,
  last_status text
)
ON CONFLICT (title, doc_number) WHERE doc_number IS NOT NULL DO UPDATE SET
  source_url = EXCLUDED.source_url,
  catalog_metadata = EXCLUDED.catalog_metadata,
  corpus_scope = EXCLUDED.corpus_scope,
  jurisdiction_code = EXCLUDED.jurisdiction_code,
  is_active = EXCLUDED.is_active,
  doc_type = EXCLUDED.doc_type,
  updated_at = now();

COMMIT;
