BEGIN;

WITH catalog AS (
  SELECT
    r.doc_type::text,
    r.doc_number::text,
    r.title::text,
    r.source_url::text,
    jsonb_strip_nulls(jsonb_build_object(
      'catalog_id', r.id,
      'catalog_order', r."order",
      'source_type', r.source_type,
      'category', r.category,
      'priority', r.priority,
      'authority', r.authority,
      'main_use', r.main_use,
      'legal_weight', r.legal_weight,
      'retrieval_rank_key', r.retrieval_rank_key,
      'corpus_role', 'guidance',
      'binding_override', true,
      'official_url', r.official_url,
      'fallback_url', r.fallback_url,
      'source_catalog_url', r.source_catalog_url,
      'resolver_title_contains', r.resolver_title_contains,
      'discovery_mode', r.discovery_mode,
      'link_match_patterns', r.link_match_patterns,
      'parse_mode', r.parse_mode,
      'extract_forms', CASE WHEN r.extract_forms THEN true ELSE NULL END,
      'rag_key_prefix', r.rag_key_prefix,
      'admin_sync_only', r.admin_sync_only,
      'sync_interval_days', r.sync_interval_days,
      'last_status', r.last_status
    )) AS catalog_metadata
  FROM jsonb_to_recordset($catalog$[
  {
    "id": "catalog-csgb-isg-yayinlari",
    "order": 1,
    "doc_type": "guide",
    "source_type": "official_guide_catalog",
    "title": "ÇSGB İş Sağlığı ve Güvenliği Yayınları Kataloğu",
    "category": "guide_catalog",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "ÇSGB tarafından yayımlanan tüm İSG rehber, kitap, el kitabı, sektör rehberi ve uygulama dokümanlarını keşfetmek",
    "legal_weight": "reference",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "doc_number": "catalog-csgb-isg-yayinlari",
    "official_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "fallback_url": "https://www.csgb.gov.tr/yayinlar/raporlar/is-sagligi-ve-guvenligi/",
    "source_catalog_url": null,
    "resolver_title_contains": null,
    "discovery_mode": "crawl_catalog_and_extract_pdf_links",
    "link_match_patterns": [
      "/Media/",
      ".pdf"
    ],
    "parse_mode": null,
    "extract_forms": false,
    "rag_key_prefix": "guide-catalog:csgb-isg-yayinlari",
    "sync_interval_days": 7,
    "admin_sync_only": true,
    "last_status": "catalog_discovery"
  },
  {
    "id": "guide-kamuda-isg-rehberi",
    "order": 2,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "Kamuda İş Sağlığı ve Güvenliği Rehberi",
    "category": "public_sector_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Kamu kurumlarında İSG organizasyonu, hizmet alımı, görevlendirme, risk değerlendirmesi, eğitim, kurul, bütçe ve ihale süreçleri",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/jt1a13o5/kamudaisgrehberi_30-01.pdf",
    "doc_number": "guide-kamuda-isg-rehberi",
    "official_url": "https://www.csgb.gov.tr/Media/jt1a13o5/kamudaisgrehberi_30-01.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_forms",
    "extract_forms": false,
    "rag_key_prefix": "guide:kamuda-isg-rehberi",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-kamu-isg-platformu",
    "order": 3,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "Kamuda İş Sağlığı ve Güvenliği / Kamu İSG Platformu Dokümanı",
    "category": "public_sector_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Kamu kurumlarına özel rehberler, kılavuzlar, kontrol listeleri, bilgi kartları ve kamu İSG uygulama çerçevesi",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/z1affwjv/kamuda-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi.pdf",
    "doc_number": "guide-kamu-isg-platformu",
    "official_url": "https://www.csgb.gov.tr/Media/z1affwjv/kamuda-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_forms",
    "extract_forms": false,
    "rag_key_prefix": "guide:kamu-isg-platformu",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-isg-kurullari-calisma-rehberi",
    "order": 4,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "İşyerlerinde İSG Kurulları Çalışma Rehberi",
    "category": "isg_board",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "İSG kurulu kurulması, kurul üyeleri, toplantı usulü, iç yönerge, tutanak, tehlike bildirim formları",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/h3cgaksi/i%C5%9Fyerlerinde-isg-kurullar%C4%B1-%C3%A7al%C4%B1%C5%9Fma-rehberi_mdb.pdf",
    "doc_number": "guide-isg-kurullari-calisma-rehberi",
    "official_url": "https://www.csgb.gov.tr/Media/h3cgaksi/i%C5%9Fyerlerinde-isg-kurullar%C4%B1-%C3%A7al%C4%B1%C5%9Fma-rehberi_mdb.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_forms",
    "extract_forms": true,
    "rag_key_prefix": "guide:isg-kurullari-calisma-rehberi",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-isg-uygulamalari",
    "order": 5,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "İş Sağlığı ve Güvenliği Uygulamaları Rehberi",
    "category": "general_isg_practice",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Aydınlatma, ergonomi, kimyasal risk, patlayıcı ortam, kapalı alan, kaldırma ekipmanı, ofis, iş hijyeni ve teknik İSG uygulamaları",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/qalg3bgm/i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-guevenli%C4%9Fi-uygulamalar%C4%B1.pdf",
    "doc_number": "guide-isg-uygulamalari",
    "official_url": "https://www.csgb.gov.tr/Media/qalg3bgm/i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-guevenli%C4%9Fi-uygulamalar%C4%B1.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_checklists",
    "extract_forms": false,
    "rag_key_prefix": "guide:isg-uygulamalari",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-yapi-islerinde-yuksekte-calisma",
    "order": 6,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "Yapı İşlerinde Yüksekte Çalışmalarda İş Sağlığı ve Güvenliği Uygulama Rehberi",
    "category": "construction_work_at_height",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Yapı işlerinde yüksekte çalışma, düşme önleme, toplu koruma, iskele, kenar koruma, çatı ve şantiye uygulamaları",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/s0jnggut/yap%C4%B1-i%C5%9Flerinde-y%C3%BCksekte-%C3%A7al%C4%B1%C5%9Fmalarda-isg-uygulama-rehberi.pdf",
    "doc_number": "guide-yapi-islerinde-yuksekte-calisma",
    "official_url": "https://www.csgb.gov.tr/Media/s0jnggut/yap%C4%B1-i%C5%9Flerinde-y%C3%BCksekte-%C3%A7al%C4%B1%C5%9Fmalarda-isg-uygulama-rehberi.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_figures_checklists",
    "extract_forms": false,
    "rag_key_prefix": "guide:yapi-islerinde-yuksekte-calisma",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-isveren-ve-vekili-isg-egitim",
    "order": 7,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "İşveren ve İşveren Vekilinin İş Sağlığı ve Güvenliği Eğitim Rehberi",
    "category": "employer_training",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "İşveren/işveren vekili İSG farkındalığı, görev ve sorumlulukların pratik anlatımı",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/mcjd25tt/isveren-ve-vekili-isg-egitim-rehberi_mdb.pdf",
    "doc_number": "guide-isveren-ve-vekili-isg-egitim",
    "official_url": "https://www.csgb.gov.tr/Media/mcjd25tt/isveren-ve-vekili-isg-egitim-rehberi_mdb.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "guide:isveren-ve-vekili-isg-egitim",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-calisma-hayatinda-ilkyardim-el-kitabi",
    "order": 8,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "Çalışma Hayatında İlk Yardım El Kitabı",
    "category": "first_aid",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "İşyerlerinde ilk yardım organizasyonu, acil müdahale bilinci ve destek elemanı eğitim içeriği",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": null,
    "doc_number": "guide-calisma-hayatinda-ilkyardim-el-kitabi",
    "official_url": null,
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": [
      "Çalışma Hayatında İlk Yardım El Kitabı",
      "İlk Yardım El Kitabı"
    ],
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "resolve_from_catalog_then_pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "guide:calisma-hayatinda-ilkyardim",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "pending"
  },
  {
    "id": "guide-metal-sektoru-isg",
    "order": 9,
    "doc_type": "guide",
    "source_type": "sector_guide",
    "title": "Metal Sektörü İşyerlerinde İş Sağlığı ve Güvenliği Rehberi",
    "category": "sector_metal",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Metal sektöründe makine, kaynak, taşlama, pres, gürültü, kimyasal ve ekipman riskleri",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/nmfdclc4/metal-sekt%C3%B6r%C3%BC-i%C5%9Fyerlerinde-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi-rehberi.pdf",
    "doc_number": "guide-metal-sektoru-isg",
    "official_url": "https://www.csgb.gov.tr/Media/nmfdclc4/metal-sekt%C3%B6r%C3%BC-i%C5%9Fyerlerinde-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi-rehberi.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_checklists",
    "extract_forms": false,
    "rag_key_prefix": "guide:metal-sektoru-isg",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-sebze-meyve-isg",
    "order": 10,
    "doc_type": "guide",
    "source_type": "sector_guide",
    "title": "Sebze ve Meyve Sektörü İş Sağlığı ve Güvenliği Rehberi",
    "category": "sector_food_agriculture_trade",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Sebze-meyve işyerleri, haller, depolama, taşıma, kayma-düşme, elle taşıma, hijyen ve soğuk ortam riskleri",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/5h5bb554/sebze-ve-meyve-rehberi-d%C3%BCzeltme.pdf",
    "doc_number": "guide-sebze-meyve-isg",
    "official_url": "https://www.csgb.gov.tr/Media/5h5bb554/sebze-ve-meyve-rehberi-d%C3%BCzeltme.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_checklists",
    "extract_forms": false,
    "rag_key_prefix": "guide:sebze-meyve-isg",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-6331-kanun-kitabi",
    "order": 11,
    "doc_type": "guide",
    "source_type": "official_book",
    "title": "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı",
    "category": "law_explainer",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "6331 sayılı Kanunun açıklamalı / uygulama destekli dokümanı",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": null,
    "doc_number": "guide-6331-kanun-kitabi",
    "official_url": null,
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": [
      "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı"
    ],
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "resolve_from_catalog_then_pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "book:6331-kanun-kitabi",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "pending"
  },
  {
    "id": "guide-6331-kanun-kitabi-en",
    "order": 12,
    "doc_type": "guide",
    "source_type": "official_book",
    "title": "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı - İngilizce",
    "category": "law_explainer_english",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Yabancı işveren, yabancı çalışan veya çok dilli RAG cevapları için İngilizce resmi kaynak",
    "legal_weight": "guidance_translation",
    "retrieval_rank_key": "official_guide",
    "source_url": null,
    "doc_number": "guide-6331-kanun-kitabi-en",
    "official_url": null,
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": [
      "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı (İngilizce)",
      "Occupational Health and Safety Law"
    ],
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "resolve_from_catalog_then_pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "book:6331-kanun-kitabi-en",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "pending"
  },
  {
    "id": "guide-avrupa-birligi-isg",
    "order": 13,
    "doc_type": "guide",
    "source_type": "official_book",
    "title": "Avrupa Birliği'nde İş Sağlığı ve Güvenliği",
    "category": "eu_osh_reference",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "AB İSG yaklaşımı, çerçeve direktifler, karşılaştırmalı İSG politikası",
    "legal_weight": "reference",
    "retrieval_rank_key": "official_guide",
    "source_url": null,
    "doc_number": "guide-avrupa-birligi-isg",
    "official_url": null,
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": [
      "Avrupa Birliği'nde İş Sağlığı ve Güvenliği",
      "Avrupa Birliği'nde İş Sağlığı ve Güvenliği"
    ],
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "resolve_from_catalog_then_pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "book:ab-isg",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "pending"
  },
  {
    "id": "guide-risk-degerlendirme-rehberleri-catalog",
    "order": 14,
    "doc_type": "guide",
    "source_type": "official_guide_catalog",
    "title": "Risk Değerlendirmesi Rehberleri Kataloğu",
    "category": "risk_assessment_guides",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı / İSGGM",
    "main_use": "Sektörel risk değerlendirmesi rehberleri, kontrol listeleri ve örnek risk analizleri",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "doc_number": "guide-risk-degerlendirme-rehberleri-catalog",
    "official_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "fallback_url": null,
    "source_catalog_url": null,
    "resolver_title_contains": [
      "Risk Değerlendirmesi Rehberi",
      "Risk Değerlendirme Rehberi",
      "Kontrol Listesi"
    ],
    "discovery_mode": "crawl_catalog_and_extract_matching_guides",
    "link_match_patterns": null,
    "parse_mode": null,
    "extract_forms": false,
    "rag_key_prefix": "guide-catalog:risk-degerlendirme",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "catalog_discovery"
  },
  {
    "id": "guide-sektor-rehberleri-catalog",
    "order": 15,
    "doc_type": "guide",
    "source_type": "official_guide_catalog",
    "title": "ÇSGB / İSGGM Sektörel İş Sağlığı ve Güvenliği Rehberleri Kataloğu",
    "category": "sector_guides",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı / İSGGM",
    "main_use": "Sektöre özel rehberlerin otomatik keşfi: metal, gıda, tarım, tekstil, mobilya, inşaat, hizmet, depo, lojistik vb.",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "doc_number": "guide-sektor-rehberleri-catalog",
    "official_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "fallback_url": null,
    "source_catalog_url": null,
    "resolver_title_contains": [
      "Sektörü İşyerlerinde İş Sağlığı ve Güvenliği Rehberi",
      "Sektöründe İş Sağlığı ve Güvenliği Rehberi",
      "İş Sağlığı ve Güvenliği Rehberi"
    ],
    "discovery_mode": "crawl_catalog_and_extract_matching_guides",
    "link_match_patterns": null,
    "parse_mode": null,
    "extract_forms": false,
    "rag_key_prefix": "guide-catalog:sektor-rehberleri",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "catalog_discovery"
  },
  {
    "id": "guide-form-kontrol-listeleri-catalog",
    "order": 16,
    "doc_type": "guide",
    "source_type": "official_template_catalog",
    "title": "İSG Formları, Kontrol Listeleri ve Bilgi Kartları Kataloğu",
    "category": "forms_checklists",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı / İSGGM",
    "main_use": "Kurul tutanağı, tehlike bildirim formu, kontrol listesi, iç yönerge ve uygulama formları",
    "legal_weight": "template",
    "retrieval_rank_key": "official_template",
    "source_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "doc_number": "guide-form-kontrol-listeleri-catalog",
    "official_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "fallback_url": null,
    "source_catalog_url": null,
    "resolver_title_contains": [
      "Kontrol Listesi",
      "Form",
      "Bilgi Kartı",
      "Talimat",
      "İç Yönerge",
      "Tutanak"
    ],
    "discovery_mode": "crawl_catalog_extract_forms_and_templates",
    "link_match_patterns": null,
    "parse_mode": null,
    "extract_forms": false,
    "rag_key_prefix": "template-catalog:isg-form-kontrol-listeleri",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "catalog_discovery"
  }
]$catalog$::jsonb) AS r(
  id text,
  "order" int,
  doc_type text,
  source_type text,
  title text,
  category text,
  priority text,
  authority text,
  main_use text,
  legal_weight text,
  retrieval_rank_key text,
  source_url text,
  doc_number text,
  official_url text,
  fallback_url text,
  source_catalog_url text,
  resolver_title_contains jsonb,
  discovery_mode text,
  link_match_patterns jsonb,
  parse_mode text,
  extract_forms boolean,
  rag_key_prefix text,
  sync_interval_days int,
  admin_sync_only boolean,
  last_status text
)
)
UPDATE public.legal_documents ld
SET
  doc_number = c.doc_number,
  source_url = c.source_url,
  catalog_metadata = c.catalog_metadata,
  corpus_scope = 'official',
  jurisdiction_code = 'TR',
  is_active = true,
  doc_type = c.doc_type,
  updated_at = now()
FROM catalog c
WHERE ld.title = c.title
  AND ld.doc_type = 'guide';

INSERT INTO public.legal_documents (
  doc_type,
  doc_number,
  title,
  source_url,
  corpus_scope,
  jurisdiction_code,
  is_active,
  catalog_metadata
)
SELECT
  r.doc_type::text,
  r.doc_number::text,
  r.title::text,
  r.source_url::text,
  'official'::text,
  'TR'::text,
  true,
  jsonb_strip_nulls(jsonb_build_object(
      'catalog_id', r.id,
      'catalog_order', r."order",
      'source_type', r.source_type,
      'category', r.category,
      'priority', r.priority,
      'authority', r.authority,
      'main_use', r.main_use,
      'legal_weight', r.legal_weight,
      'retrieval_rank_key', r.retrieval_rank_key,
      'corpus_role', 'guidance',
      'binding_override', true,
      'official_url', r.official_url,
      'fallback_url', r.fallback_url,
      'source_catalog_url', r.source_catalog_url,
      'resolver_title_contains', r.resolver_title_contains,
      'discovery_mode', r.discovery_mode,
      'link_match_patterns', r.link_match_patterns,
      'parse_mode', r.parse_mode,
      'extract_forms', CASE WHEN r.extract_forms THEN true ELSE NULL END,
      'rag_key_prefix', r.rag_key_prefix,
      'admin_sync_only', r.admin_sync_only,
      'sync_interval_days', r.sync_interval_days,
      'last_status', r.last_status
    ))
FROM jsonb_to_recordset($catalog$[
  {
    "id": "catalog-csgb-isg-yayinlari",
    "order": 1,
    "doc_type": "guide",
    "source_type": "official_guide_catalog",
    "title": "ÇSGB İş Sağlığı ve Güvenliği Yayınları Kataloğu",
    "category": "guide_catalog",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "ÇSGB tarafından yayımlanan tüm İSG rehber, kitap, el kitabı, sektör rehberi ve uygulama dokümanlarını keşfetmek",
    "legal_weight": "reference",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "doc_number": "catalog-csgb-isg-yayinlari",
    "official_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "fallback_url": "https://www.csgb.gov.tr/yayinlar/raporlar/is-sagligi-ve-guvenligi/",
    "source_catalog_url": null,
    "resolver_title_contains": null,
    "discovery_mode": "crawl_catalog_and_extract_pdf_links",
    "link_match_patterns": [
      "/Media/",
      ".pdf"
    ],
    "parse_mode": null,
    "extract_forms": false,
    "rag_key_prefix": "guide-catalog:csgb-isg-yayinlari",
    "sync_interval_days": 7,
    "admin_sync_only": true,
    "last_status": "catalog_discovery"
  },
  {
    "id": "guide-kamuda-isg-rehberi",
    "order": 2,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "Kamuda İş Sağlığı ve Güvenliği Rehberi",
    "category": "public_sector_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Kamu kurumlarında İSG organizasyonu, hizmet alımı, görevlendirme, risk değerlendirmesi, eğitim, kurul, bütçe ve ihale süreçleri",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/jt1a13o5/kamudaisgrehberi_30-01.pdf",
    "doc_number": "guide-kamuda-isg-rehberi",
    "official_url": "https://www.csgb.gov.tr/Media/jt1a13o5/kamudaisgrehberi_30-01.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_forms",
    "extract_forms": false,
    "rag_key_prefix": "guide:kamuda-isg-rehberi",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-kamu-isg-platformu",
    "order": 3,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "Kamuda İş Sağlığı ve Güvenliği / Kamu İSG Platformu Dokümanı",
    "category": "public_sector_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Kamu kurumlarına özel rehberler, kılavuzlar, kontrol listeleri, bilgi kartları ve kamu İSG uygulama çerçevesi",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/z1affwjv/kamuda-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi.pdf",
    "doc_number": "guide-kamu-isg-platformu",
    "official_url": "https://www.csgb.gov.tr/Media/z1affwjv/kamuda-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_forms",
    "extract_forms": false,
    "rag_key_prefix": "guide:kamu-isg-platformu",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-isg-kurullari-calisma-rehberi",
    "order": 4,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "İşyerlerinde İSG Kurulları Çalışma Rehberi",
    "category": "isg_board",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "İSG kurulu kurulması, kurul üyeleri, toplantı usulü, iç yönerge, tutanak, tehlike bildirim formları",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/h3cgaksi/i%C5%9Fyerlerinde-isg-kurullar%C4%B1-%C3%A7al%C4%B1%C5%9Fma-rehberi_mdb.pdf",
    "doc_number": "guide-isg-kurullari-calisma-rehberi",
    "official_url": "https://www.csgb.gov.tr/Media/h3cgaksi/i%C5%9Fyerlerinde-isg-kurullar%C4%B1-%C3%A7al%C4%B1%C5%9Fma-rehberi_mdb.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_forms",
    "extract_forms": true,
    "rag_key_prefix": "guide:isg-kurullari-calisma-rehberi",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-isg-uygulamalari",
    "order": 5,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "İş Sağlığı ve Güvenliği Uygulamaları Rehberi",
    "category": "general_isg_practice",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Aydınlatma, ergonomi, kimyasal risk, patlayıcı ortam, kapalı alan, kaldırma ekipmanı, ofis, iş hijyeni ve teknik İSG uygulamaları",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/qalg3bgm/i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-guevenli%C4%9Fi-uygulamalar%C4%B1.pdf",
    "doc_number": "guide-isg-uygulamalari",
    "official_url": "https://www.csgb.gov.tr/Media/qalg3bgm/i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-guevenli%C4%9Fi-uygulamalar%C4%B1.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_checklists",
    "extract_forms": false,
    "rag_key_prefix": "guide:isg-uygulamalari",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-yapi-islerinde-yuksekte-calisma",
    "order": 6,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "Yapı İşlerinde Yüksekte Çalışmalarda İş Sağlığı ve Güvenliği Uygulama Rehberi",
    "category": "construction_work_at_height",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Yapı işlerinde yüksekte çalışma, düşme önleme, toplu koruma, iskele, kenar koruma, çatı ve şantiye uygulamaları",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/s0jnggut/yap%C4%B1-i%C5%9Flerinde-y%C3%BCksekte-%C3%A7al%C4%B1%C5%9Fmalarda-isg-uygulama-rehberi.pdf",
    "doc_number": "guide-yapi-islerinde-yuksekte-calisma",
    "official_url": "https://www.csgb.gov.tr/Media/s0jnggut/yap%C4%B1-i%C5%9Flerinde-y%C3%BCksekte-%C3%A7al%C4%B1%C5%9Fmalarda-isg-uygulama-rehberi.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_figures_checklists",
    "extract_forms": false,
    "rag_key_prefix": "guide:yapi-islerinde-yuksekte-calisma",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-isveren-ve-vekili-isg-egitim",
    "order": 7,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "İşveren ve İşveren Vekilinin İş Sağlığı ve Güvenliği Eğitim Rehberi",
    "category": "employer_training",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "İşveren/işveren vekili İSG farkındalığı, görev ve sorumlulukların pratik anlatımı",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/mcjd25tt/isveren-ve-vekili-isg-egitim-rehberi_mdb.pdf",
    "doc_number": "guide-isveren-ve-vekili-isg-egitim",
    "official_url": "https://www.csgb.gov.tr/Media/mcjd25tt/isveren-ve-vekili-isg-egitim-rehberi_mdb.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "guide:isveren-ve-vekili-isg-egitim",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-calisma-hayatinda-ilkyardim-el-kitabi",
    "order": 8,
    "doc_type": "guide",
    "source_type": "official_guide",
    "title": "Çalışma Hayatında İlk Yardım El Kitabı",
    "category": "first_aid",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "İşyerlerinde ilk yardım organizasyonu, acil müdahale bilinci ve destek elemanı eğitim içeriği",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": null,
    "doc_number": "guide-calisma-hayatinda-ilkyardim-el-kitabi",
    "official_url": null,
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": [
      "Çalışma Hayatında İlk Yardım El Kitabı",
      "İlk Yardım El Kitabı"
    ],
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "resolve_from_catalog_then_pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "guide:calisma-hayatinda-ilkyardim",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "pending"
  },
  {
    "id": "guide-metal-sektoru-isg",
    "order": 9,
    "doc_type": "guide",
    "source_type": "sector_guide",
    "title": "Metal Sektörü İşyerlerinde İş Sağlığı ve Güvenliği Rehberi",
    "category": "sector_metal",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Metal sektöründe makine, kaynak, taşlama, pres, gürültü, kimyasal ve ekipman riskleri",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/nmfdclc4/metal-sekt%C3%B6r%C3%BC-i%C5%9Fyerlerinde-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi-rehberi.pdf",
    "doc_number": "guide-metal-sektoru-isg",
    "official_url": "https://www.csgb.gov.tr/Media/nmfdclc4/metal-sekt%C3%B6r%C3%BC-i%C5%9Fyerlerinde-i%C5%9F-sa%C4%9Fl%C4%B1%C4%9F%C4%B1-ve-g%C3%BCvenli%C4%9Fi-rehberi.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_checklists",
    "extract_forms": false,
    "rag_key_prefix": "guide:metal-sektoru-isg",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-sebze-meyve-isg",
    "order": 10,
    "doc_type": "guide",
    "source_type": "sector_guide",
    "title": "Sebze ve Meyve Sektörü İş Sağlığı ve Güvenliği Rehberi",
    "category": "sector_food_agriculture_trade",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Sebze-meyve işyerleri, haller, depolama, taşıma, kayma-düşme, elle taşıma, hijyen ve soğuk ortam riskleri",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/Media/5h5bb554/sebze-ve-meyve-rehberi-d%C3%BCzeltme.pdf",
    "doc_number": "guide-sebze-meyve-isg",
    "official_url": "https://www.csgb.gov.tr/Media/5h5bb554/sebze-ve-meyve-rehberi-d%C3%BCzeltme.pdf",
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": null,
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "pdf_sections_tables_checklists",
    "extract_forms": false,
    "rag_key_prefix": "guide:sebze-meyve-isg",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "resolved"
  },
  {
    "id": "guide-6331-kanun-kitabi",
    "order": 11,
    "doc_type": "guide",
    "source_type": "official_book",
    "title": "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı",
    "category": "law_explainer",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "6331 sayılı Kanunun açıklamalı / uygulama destekli dokümanı",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": null,
    "doc_number": "guide-6331-kanun-kitabi",
    "official_url": null,
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": [
      "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı"
    ],
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "resolve_from_catalog_then_pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "book:6331-kanun-kitabi",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "pending"
  },
  {
    "id": "guide-6331-kanun-kitabi-en",
    "order": 12,
    "doc_type": "guide",
    "source_type": "official_book",
    "title": "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı - İngilizce",
    "category": "law_explainer_english",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Yabancı işveren, yabancı çalışan veya çok dilli RAG cevapları için İngilizce resmi kaynak",
    "legal_weight": "guidance_translation",
    "retrieval_rank_key": "official_guide",
    "source_url": null,
    "doc_number": "guide-6331-kanun-kitabi-en",
    "official_url": null,
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": [
      "6331 Sayılı İş Sağlığı ve Güvenliği Kanunu Kitabı (İngilizce)",
      "Occupational Health and Safety Law"
    ],
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "resolve_from_catalog_then_pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "book:6331-kanun-kitabi-en",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "pending"
  },
  {
    "id": "guide-avrupa-birligi-isg",
    "order": 13,
    "doc_type": "guide",
    "source_type": "official_book",
    "title": "Avrupa Birliği'nde İş Sağlığı ve Güvenliği",
    "category": "eu_osh_reference",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "AB İSG yaklaşımı, çerçeve direktifler, karşılaştırmalı İSG politikası",
    "legal_weight": "reference",
    "retrieval_rank_key": "official_guide",
    "source_url": null,
    "doc_number": "guide-avrupa-birligi-isg",
    "official_url": null,
    "fallback_url": null,
    "source_catalog_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "resolver_title_contains": [
      "Avrupa Birliği'nde İş Sağlığı ve Güvenliği",
      "Avrupa Birliği'nde İş Sağlığı ve Güvenliği"
    ],
    "discovery_mode": null,
    "link_match_patterns": null,
    "parse_mode": "resolve_from_catalog_then_pdf_sections",
    "extract_forms": false,
    "rag_key_prefix": "book:ab-isg",
    "sync_interval_days": 30,
    "admin_sync_only": true,
    "last_status": "pending"
  },
  {
    "id": "guide-risk-degerlendirme-rehberleri-catalog",
    "order": 14,
    "doc_type": "guide",
    "source_type": "official_guide_catalog",
    "title": "Risk Değerlendirmesi Rehberleri Kataloğu",
    "category": "risk_assessment_guides",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı / İSGGM",
    "main_use": "Sektörel risk değerlendirmesi rehberleri, kontrol listeleri ve örnek risk analizleri",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "doc_number": "guide-risk-degerlendirme-rehberleri-catalog",
    "official_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "fallback_url": null,
    "source_catalog_url": null,
    "resolver_title_contains": [
      "Risk Değerlendirmesi Rehberi",
      "Risk Değerlendirme Rehberi",
      "Kontrol Listesi"
    ],
    "discovery_mode": "crawl_catalog_and_extract_matching_guides",
    "link_match_patterns": null,
    "parse_mode": null,
    "extract_forms": false,
    "rag_key_prefix": "guide-catalog:risk-degerlendirme",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "catalog_discovery"
  },
  {
    "id": "guide-sektor-rehberleri-catalog",
    "order": 15,
    "doc_type": "guide",
    "source_type": "official_guide_catalog",
    "title": "ÇSGB / İSGGM Sektörel İş Sağlığı ve Güvenliği Rehberleri Kataloğu",
    "category": "sector_guides",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı / İSGGM",
    "main_use": "Sektöre özel rehberlerin otomatik keşfi: metal, gıda, tarım, tekstil, mobilya, inşaat, hizmet, depo, lojistik vb.",
    "legal_weight": "guidance",
    "retrieval_rank_key": "official_guide",
    "source_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "doc_number": "guide-sektor-rehberleri-catalog",
    "official_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "fallback_url": null,
    "source_catalog_url": null,
    "resolver_title_contains": [
      "Sektörü İşyerlerinde İş Sağlığı ve Güvenliği Rehberi",
      "Sektöründe İş Sağlığı ve Güvenliği Rehberi",
      "İş Sağlığı ve Güvenliği Rehberi"
    ],
    "discovery_mode": "crawl_catalog_and_extract_matching_guides",
    "link_match_patterns": null,
    "parse_mode": null,
    "extract_forms": false,
    "rag_key_prefix": "guide-catalog:sektor-rehberleri",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "catalog_discovery"
  },
  {
    "id": "guide-form-kontrol-listeleri-catalog",
    "order": 16,
    "doc_type": "guide",
    "source_type": "official_template_catalog",
    "title": "İSG Formları, Kontrol Listeleri ve Bilgi Kartları Kataloğu",
    "category": "forms_checklists",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı / İSGGM",
    "main_use": "Kurul tutanağı, tehlike bildirim formu, kontrol listesi, iç yönerge ve uygulama formları",
    "legal_weight": "template",
    "retrieval_rank_key": "official_template",
    "source_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "doc_number": "guide-form-kontrol-listeleri-catalog",
    "official_url": "https://www.csgb.gov.tr/yayinlar/raporlar/%C4%B1s-sagligi-ve-guvenligi/",
    "fallback_url": null,
    "source_catalog_url": null,
    "resolver_title_contains": [
      "Kontrol Listesi",
      "Form",
      "Bilgi Kartı",
      "Talimat",
      "İç Yönerge",
      "Tutanak"
    ],
    "discovery_mode": "crawl_catalog_extract_forms_and_templates",
    "link_match_patterns": null,
    "parse_mode": null,
    "extract_forms": false,
    "rag_key_prefix": "template-catalog:isg-form-kontrol-listeleri",
    "sync_interval_days": 14,
    "admin_sync_only": true,
    "last_status": "catalog_discovery"
  }
]$catalog$::jsonb) AS r(
  id text,
  "order" int,
  doc_type text,
  source_type text,
  title text,
  category text,
  priority text,
  authority text,
  main_use text,
  legal_weight text,
  retrieval_rank_key text,
  source_url text,
  doc_number text,
  official_url text,
  fallback_url text,
  source_catalog_url text,
  resolver_title_contains jsonb,
  discovery_mode text,
  link_match_patterns jsonb,
  parse_mode text,
  extract_forms boolean,
  rag_key_prefix text,
  sync_interval_days int,
  admin_sync_only boolean,
  last_status text
)
ON CONFLICT (title, doc_number) WHERE doc_number IS NOT NULL DO UPDATE SET
  source_url = EXCLUDED.source_url,
  catalog_metadata = EXCLUDED.catalog_metadata,
  corpus_scope = EXCLUDED.corpus_scope,
  jurisdiction_code = EXCLUDED.jurisdiction_code,
  is_active = EXCLUDED.is_active,
  doc_type = EXCLUDED.doc_type,
  updated_at = now();

COMMIT;
