BEGIN;

WITH catalog AS (
  SELECT
    r.doc_type::text,
    r.doc_number::text,
    r.title::text,
    r.source_url::text,
    jsonb_strip_nulls(jsonb_build_object(
      'catalog_id', r.id,
      'catalog_order', r."order",
      'source_type', r.source_type,
      'category', r.category,
      'priority', r.priority,
      'authority', r.authority,
      'main_use', r.main_use,
      'mevzuat_tur', r.mevzuat_tur,
      'mevzuat_tertip', r.mevzuat_tertip,
      'mevzuat_lookup_url', r.mevzuat_lookup_url,
      'resmi_gazete_issue_url', r.resmi_gazete_issue_url,
      'resmi_gazete_issue_no', r.resmi_gazete_issue_no,
      'resmi_gazete_lookup_url', r.resmi_gazete_lookup_url,
      'first_publication_date', r.first_publication_date,
      'official_lookup_url', r.official_lookup_url,
      'official_url', r.official_url,
      'change_resolver_title_contains', r.change_resolver_title_contains,
      'resolver_title_contains', r.resolver_title_contains,
      'expected_document_pattern', r.expected_document_pattern,
      'rag_key_prefix', r.rag_key_prefix,
      'admin_sync_only', r.admin_sync_only,
      'sync_interval_days', r.sync_interval_days,
      'canonical_resolved', (r.source_url IS NOT NULL AND r.source_url ~* 'mevzuat\.gov\.tr.*MevzuatNo='),
      'last_status', CASE
        WHEN r.source_type = 'annual_table' THEN 'external_table'
        WHEN r.source_url IS NOT NULL AND r.source_url ~* 'mevzuat\.gov\.tr.*MevzuatNo=' THEN 'resolved'
        WHEN r.source_url IS NOT NULL AND r.source_url !~* 'mevzuat\.gov\.tr' THEN 'external_source'
        ELSE 'pending'
      END
    )) AS catalog_metadata
  FROM jsonb_to_recordset($catalog$[
  {
    "id": "teblig-isyeri-tehlike-siniflari",
    "order": 1,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "İş Sağlığı ve Güvenliğine İlişkin İşyeri Tehlike Sınıfları Tebliği",
    "category": "core_isg_tehlike_sinifi",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "NACE kodu / işyeri tehlike sınıfı / az tehlikeli-tehlikeli-çok tehlikeli ayrımı",
    "source_url": null,
    "doc_number": "teblig-isyeri-tehlike-siniflari",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": "https://www.resmigazete.gov.tr/eskiler/2012/12/20121226.htm",
    "resmi_gazete_issue_no": "28509",
    "resmi_gazete_lookup_url": null,
    "first_publication_date": "2012-12-26",
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": [
      "İş Sağlığı ve Güvenliğine İlişkin İşyeri Tehlike Sınıfları Tebliğinde Değişiklik Yapılmasına Dair Tebliğ"
    ],
    "resolver_title_contains": null,
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:isyeri-tehlike-siniflari",
    "sync_interval_days": 7,
    "admin_sync_only": true
  },
  {
    "id": "teblig-is-ekipmanlari-periyodik-kontrol-yetkili-kisi",
    "order": 2,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "İş Ekipmanlarının Periyodik Kontrollerini Yapmaya Yetkili Kişilerin Kayıt ve Eğitimlerine İlişkin Tebliğ",
    "category": "core_isg_periyodik_kontrol",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Periyodik kontrol yapacak kişilerin kayıt, eğitim, yetki ve belge süreçleri",
    "source_url": null,
    "doc_number": "teblig-is-ekipmanlari-periyodik-kontrol-yetkili-kisi",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": "https://www.resmigazete.gov.tr/eskiler/2017/10/20171001.htm",
    "resmi_gazete_issue_no": "30197",
    "resmi_gazete_lookup_url": null,
    "first_publication_date": "2017-10-01",
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": [
      "İş Ekipmanlarının Periyodik Kontrollerini Yapmaya Yetkili Kişilerin Kayıt ve Eğitimlerine İlişkin Tebliğde Değişiklik Yapılmasına Dair Tebliğ"
    ],
    "resolver_title_contains": null,
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:is-ekipmanlari-periyodik-kontrol-yetkili-kisi",
    "sync_interval_days": 7,
    "admin_sync_only": true
  },
  {
    "id": "teblig-asbest-sokumu-egitim-programlari",
    "order": 3,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "Asbest Sökümü ile İlgili Eğitim Programlarına İlişkin Tebliğ",
    "category": "core_isg_asbest",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Asbest söküm uzmanı ve asbest söküm çalışanı eğitim programları",
    "source_url": null,
    "doc_number": "teblig-asbest-sokumu-egitim-programlari",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/06/20130629.htm",
    "resmi_gazete_issue_no": "28692",
    "resmi_gazete_lookup_url": null,
    "first_publication_date": "2013-06-29",
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": [
      "Asbest Sökümü ile İlgili Eğitim Programlarına İlişkin Tebliğde Değişiklik Yapılmasına Dair Tebliğ"
    ],
    "resolver_title_contains": null,
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:asbest-sokumu-egitim-programlari",
    "sync_interval_days": 7,
    "admin_sync_only": true
  },
  {
    "id": "table-6331-idari-para-cezalari",
    "order": 4,
    "doc_type": "announcement",
    "source_type": "annual_table",
    "title": "6331 Sayılı İş Sağlığı ve Güvenliği Kanununa Göre Uygulanacak İdari Para Cezaları",
    "category": "core_isg_idari_para_cezalari",
    "priority": "critical",
    "authority": "İş Sağlığı ve Güvenliği Genel Müdürlüğü",
    "main_use": "6331 kapsamındaki ihlallerin yıllık idari para cezası tutarları",
    "source_url": "https://www.csgb.gov.tr/isggm/tr/%C4%B1sg-hizmetleri/idari-para-cezalari/",
    "doc_number": "table-6331-idari-para-cezalari",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": null,
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": null,
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": "https://www.csgb.gov.tr/isggm/tr/%C4%B1sg-hizmetleri/idari-para-cezalari/",
    "change_resolver_title_contains": null,
    "resolver_title_contains": null,
    "expected_document_pattern": [
      "6331 SAYILI İŞ SAĞLIĞI VE GÜVENLİĞİ KANUNUNA GÖRE 2026 YILINDA UYGULANACAK İDARİ PARA CEZALARI",
      "6331 SAYILI İŞ SAĞLIĞI VE GÜVENLİĞİ KANUNUNA GÖRE 2025 YILINDA UYGULANACAK İDARİ PARA CEZALARI"
    ],
    "rag_key_prefix": "table:6331-idari-para-cezalari",
    "sync_interval_days": 7,
    "admin_sync_only": true
  },
  {
    "id": "teblig-vuk-yeniden-degerleme-orani",
    "order": 5,
    "doc_type": "communique",
    "source_type": "annual_communique",
    "title": "Vergi Usul Kanunu Genel Tebliği - Yeniden Değerleme Oranı",
    "category": "idari_para_cezasi_hesaplama",
    "priority": "high",
    "authority": "Hazine ve Maliye Bakanlığı / Gelir İdaresi Başkanlığı",
    "main_use": "6331 idari para cezalarının yıllık yeniden değerleme hesabı için oran kaynağı",
    "source_url": null,
    "doc_number": "teblig-vuk-yeniden-degerleme-orani",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": null,
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": "https://www.gib.gov.tr/",
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Vergi Usul Kanunu Genel Tebliği",
      "Yeniden Değerleme Oranı"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:vuk-yeniden-degerleme-orani",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-tmgd",
    "order": 6,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "Tehlikeli Madde Güvenlik Danışmanlığı Hakkında Tebliğ",
    "category": "dangerous_goods_transport",
    "priority": "high",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "main_use": "Tehlikeli madde taşımacılığı yapan işletmelerde TMGD yükümlülüğü",
    "source_url": null,
    "doc_number": "teblig-tmgd",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": "https://www.resmigazete.gov.tr/eskiler/2014/05/20140522.htm",
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": null,
    "first_publication_date": "2014-05-22",
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": [
      "Tehlikeli Madde Güvenlik Danışmanlığı Hakkında Tebliğde Değişiklik"
    ],
    "resolver_title_contains": null,
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:tmgd",
    "sync_interval_days": 14,
    "admin_sync_only": true
  },
  {
    "id": "teblig-bekra-guvenlik-raporu",
    "order": 7,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "Büyük Endüstriyel Kazalarla İlgili Güvenlik Raporu Tebliği",
    "category": "major_accident_prevention",
    "priority": "sectoral_critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "main_use": "BEKRA kapsamındaki üst seviyeli kuruluşlarda güvenlik raporu içeriği",
    "source_url": null,
    "doc_number": "teblig-bekra-guvenlik-raporu",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Büyük Endüstriyel Kazalarla İlgili Güvenlik Raporu Tebliği"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:bekra-guvenlik-raporu",
    "sync_interval_days": 14,
    "admin_sync_only": true
  },
  {
    "id": "teblig-bekra-dahili-acil-durum-plani",
    "order": 8,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "Büyük Endüstriyel Kazalarla İlgili Dahili Acil Durum Planı Tebliği",
    "category": "major_accident_prevention",
    "priority": "sectoral_critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı / AFAD",
    "main_use": "BEKRA kapsamındaki kuruluşlarda dahili acil durum planı içeriği",
    "source_url": null,
    "doc_number": "teblig-bekra-dahili-acil-durum-plani",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Büyük Endüstriyel Kazalarla İlgili Dahili Acil Durum Planı Tebliği"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:bekra-dahili-acil-durum-plani",
    "sync_interval_days": 14,
    "admin_sync_only": true
  },
  {
    "id": "teblig-kimyasallar-sds-guvenlik-bilgi-formu",
    "order": 9,
    "doc_type": "communique",
    "source_type": "communique_or_regulation_related",
    "title": "Güvenlik Bilgi Formları ve kimyasal güvenlik bilgi formu yükümlülüklerine ilişkin tebliğ/değişiklik kaynakları",
    "category": "chemical_sds",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "main_use": "SDS/GBF, zararlı madde ve karışımlar, kimyasal risk değerlendirmesi",
    "source_url": null,
    "doc_number": "teblig-kimyasallar-sds-guvenlik-bilgi-formu",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Güvenlik Bilgi Formları",
      "Zararlı Maddeler ve Karışımlara İlişkin Güvenlik Bilgi Formları",
      "Kimyasalların Kaydı, Değerlendirilmesi, İzni ve Kısıtlanması",
      "Maddelerin ve Karışımların Sınıflandırılması, Etiketlenmesi ve Ambalajlanması"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:chemical-sds",
    "sync_interval_days": 14,
    "admin_sync_only": true
  },
  {
    "id": "teblig-makina-uyumlastirilmis-standartlar",
    "order": 10,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Makina Emniyeti Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "machinery_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "main_use": "Makine emniyeti, CE, uygunluk değerlendirmesi ve teknik standart bağlantısı",
    "source_url": null,
    "doc_number": "teblig-makina-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Makina Emniyeti Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar",
      "Makine Emniyeti Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:makina-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-kkd-uyumlastirilmis-standartlar",
    "order": 11,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Kişisel Koruyucu Donanım Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "ppe_product_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "main_use": "KKD uygunluk, CE, standart ve ürün güvenliği bağlantısı",
    "source_url": null,
    "doc_number": "teblig-kkd-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Kişisel Koruyucu Donanım Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar",
      "Kişisel Koruyucu Donanım Yönetmeliği Kapsamında Uyumlaştırılmış Ulusal Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:kkd-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-basincili-ekipman-uyumlastirilmis-standartlar",
    "order": 12,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Basınçlı Ekipmanlar Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "pressure_equipment_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "main_use": "Basınçlı kap, kazan, tank, kompresör ve basınçlı sistem uygunluğu",
    "source_url": null,
    "doc_number": "teblig-basincili-ekipman-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Basınçlı Ekipmanlar Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:basincili-ekipman-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-atex-uyumlastirilmis-standartlar",
    "order": 13,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Muhtemel Patlayıcı Ortamda Kullanılan Teçhizat ve Koruyucu Sistemler ile İlgili Yönetmelik Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "atex_equipment_safety",
    "priority": "sectoral_critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "main_use": "ATEX ekipman, patlayıcı ortam, CE ve uygunluk değerlendirmesi",
    "source_url": null,
    "doc_number": "teblig-atex-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Muhtemel Patlayıcı Ortamda Kullanılan Teçhizat",
      "Koruyucu Sistemler",
      "Uyumlaştırılmış Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:atex-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-yapi-malzemeleri-uyumlastirilmis-standartlar",
    "order": 14,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Yapı Malzemeleri Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "construction_product_safety",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "main_use": "Yapı malzemeleri, şantiye ve yapı güvenliğiyle bağlantılı ürün standardı kaynakları",
    "source_url": null,
    "doc_number": "teblig-yapi-malzemeleri-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Yapı Malzemeleri Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:yapi-malzemeleri-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  }
]$catalog$::jsonb) AS r(
    id text,
    "order" int,
    doc_type text,
    source_type text,
    title text,
    category text,
    priority text,
    authority text,
    main_use text,
    source_url text,
    doc_number text,
    mevzuat_tur int,
    mevzuat_tertip int,
    mevzuat_lookup_url text,
    resmi_gazete_issue_url text,
    resmi_gazete_issue_no text,
    resmi_gazete_lookup_url text,
    first_publication_date text,
    official_lookup_url text,
    official_url text,
    change_resolver_title_contains jsonb,
    resolver_title_contains jsonb,
    expected_document_pattern jsonb,
    rag_key_prefix text,
    sync_interval_days int,
    admin_sync_only boolean
  )
)
UPDATE public.legal_documents ld
SET
  doc_number = c.doc_number,
  source_url = c.source_url,
  catalog_metadata = c.catalog_metadata,
  corpus_scope = 'official',
  jurisdiction_code = 'TR',
  is_active = true,
  doc_type = c.doc_type,
  updated_at = now()
FROM catalog c
WHERE ld.title = c.title
  AND ld.doc_type IN ('communique', 'announcement');

INSERT INTO public.legal_documents (
  doc_type,
  doc_number,
  title,
  source_url,
  corpus_scope,
  jurisdiction_code,
  is_active,
  catalog_metadata
)
SELECT
  r.doc_type::text,
  r.doc_number::text,
  r.title::text,
  r.source_url::text,
  'official'::text,
  'TR'::text,
  true,
  jsonb_strip_nulls(jsonb_build_object(
    'catalog_id', r.id,
    'catalog_order', r."order",
    'source_type', r.source_type,
    'category', r.category,
    'priority', r.priority,
    'authority', r.authority,
    'main_use', r.main_use,
    'mevzuat_tur', r.mevzuat_tur,
    'mevzuat_tertip', r.mevzuat_tertip,
    'mevzuat_lookup_url', r.mevzuat_lookup_url,
    'resmi_gazete_issue_url', r.resmi_gazete_issue_url,
    'resmi_gazete_issue_no', r.resmi_gazete_issue_no,
    'resmi_gazete_lookup_url', r.resmi_gazete_lookup_url,
    'first_publication_date', r.first_publication_date,
    'official_lookup_url', r.official_lookup_url,
    'official_url', r.official_url,
    'change_resolver_title_contains', r.change_resolver_title_contains,
    'resolver_title_contains', r.resolver_title_contains,
    'expected_document_pattern', r.expected_document_pattern,
    'rag_key_prefix', r.rag_key_prefix,
    'admin_sync_only', r.admin_sync_only,
    'sync_interval_days', r.sync_interval_days,
    'canonical_resolved', (r.source_url IS NOT NULL AND r.source_url ~* 'mevzuat\.gov\.tr.*MevzuatNo='),
    'last_status', CASE
      WHEN r.source_type = 'annual_table' THEN 'external_table'
      WHEN r.source_url IS NOT NULL AND r.source_url ~* 'mevzuat\.gov\.tr.*MevzuatNo=' THEN 'resolved'
      WHEN r.source_url IS NOT NULL AND r.source_url !~* 'mevzuat\.gov\.tr' THEN 'external_source'
      ELSE 'pending'
    END
  ))
FROM jsonb_to_recordset($catalog$[
  {
    "id": "teblig-isyeri-tehlike-siniflari",
    "order": 1,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "İş Sağlığı ve Güvenliğine İlişkin İşyeri Tehlike Sınıfları Tebliği",
    "category": "core_isg_tehlike_sinifi",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "NACE kodu / işyeri tehlike sınıfı / az tehlikeli-tehlikeli-çok tehlikeli ayrımı",
    "source_url": null,
    "doc_number": "teblig-isyeri-tehlike-siniflari",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": "https://www.resmigazete.gov.tr/eskiler/2012/12/20121226.htm",
    "resmi_gazete_issue_no": "28509",
    "resmi_gazete_lookup_url": null,
    "first_publication_date": "2012-12-26",
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": [
      "İş Sağlığı ve Güvenliğine İlişkin İşyeri Tehlike Sınıfları Tebliğinde Değişiklik Yapılmasına Dair Tebliğ"
    ],
    "resolver_title_contains": null,
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:isyeri-tehlike-siniflari",
    "sync_interval_days": 7,
    "admin_sync_only": true
  },
  {
    "id": "teblig-is-ekipmanlari-periyodik-kontrol-yetkili-kisi",
    "order": 2,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "İş Ekipmanlarının Periyodik Kontrollerini Yapmaya Yetkili Kişilerin Kayıt ve Eğitimlerine İlişkin Tebliğ",
    "category": "core_isg_periyodik_kontrol",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Periyodik kontrol yapacak kişilerin kayıt, eğitim, yetki ve belge süreçleri",
    "source_url": null,
    "doc_number": "teblig-is-ekipmanlari-periyodik-kontrol-yetkili-kisi",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": "https://www.resmigazete.gov.tr/eskiler/2017/10/20171001.htm",
    "resmi_gazete_issue_no": "30197",
    "resmi_gazete_lookup_url": null,
    "first_publication_date": "2017-10-01",
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": [
      "İş Ekipmanlarının Periyodik Kontrollerini Yapmaya Yetkili Kişilerin Kayıt ve Eğitimlerine İlişkin Tebliğde Değişiklik Yapılmasına Dair Tebliğ"
    ],
    "resolver_title_contains": null,
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:is-ekipmanlari-periyodik-kontrol-yetkili-kisi",
    "sync_interval_days": 7,
    "admin_sync_only": true
  },
  {
    "id": "teblig-asbest-sokumu-egitim-programlari",
    "order": 3,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "Asbest Sökümü ile İlgili Eğitim Programlarına İlişkin Tebliğ",
    "category": "core_isg_asbest",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "main_use": "Asbest söküm uzmanı ve asbest söküm çalışanı eğitim programları",
    "source_url": null,
    "doc_number": "teblig-asbest-sokumu-egitim-programlari",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/06/20130629.htm",
    "resmi_gazete_issue_no": "28692",
    "resmi_gazete_lookup_url": null,
    "first_publication_date": "2013-06-29",
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": [
      "Asbest Sökümü ile İlgili Eğitim Programlarına İlişkin Tebliğde Değişiklik Yapılmasına Dair Tebliğ"
    ],
    "resolver_title_contains": null,
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:asbest-sokumu-egitim-programlari",
    "sync_interval_days": 7,
    "admin_sync_only": true
  },
  {
    "id": "table-6331-idari-para-cezalari",
    "order": 4,
    "doc_type": "announcement",
    "source_type": "annual_table",
    "title": "6331 Sayılı İş Sağlığı ve Güvenliği Kanununa Göre Uygulanacak İdari Para Cezaları",
    "category": "core_isg_idari_para_cezalari",
    "priority": "critical",
    "authority": "İş Sağlığı ve Güvenliği Genel Müdürlüğü",
    "main_use": "6331 kapsamındaki ihlallerin yıllık idari para cezası tutarları",
    "source_url": "https://www.csgb.gov.tr/isggm/tr/%C4%B1sg-hizmetleri/idari-para-cezalari/",
    "doc_number": "table-6331-idari-para-cezalari",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": null,
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": null,
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": "https://www.csgb.gov.tr/isggm/tr/%C4%B1sg-hizmetleri/idari-para-cezalari/",
    "change_resolver_title_contains": null,
    "resolver_title_contains": null,
    "expected_document_pattern": [
      "6331 SAYILI İŞ SAĞLIĞI VE GÜVENLİĞİ KANUNUNA GÖRE 2026 YILINDA UYGULANACAK İDARİ PARA CEZALARI",
      "6331 SAYILI İŞ SAĞLIĞI VE GÜVENLİĞİ KANUNUNA GÖRE 2025 YILINDA UYGULANACAK İDARİ PARA CEZALARI"
    ],
    "rag_key_prefix": "table:6331-idari-para-cezalari",
    "sync_interval_days": 7,
    "admin_sync_only": true
  },
  {
    "id": "teblig-vuk-yeniden-degerleme-orani",
    "order": 5,
    "doc_type": "communique",
    "source_type": "annual_communique",
    "title": "Vergi Usul Kanunu Genel Tebliği - Yeniden Değerleme Oranı",
    "category": "idari_para_cezasi_hesaplama",
    "priority": "high",
    "authority": "Hazine ve Maliye Bakanlığı / Gelir İdaresi Başkanlığı",
    "main_use": "6331 idari para cezalarının yıllık yeniden değerleme hesabı için oran kaynağı",
    "source_url": null,
    "doc_number": "teblig-vuk-yeniden-degerleme-orani",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": null,
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": "https://www.gib.gov.tr/",
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Vergi Usul Kanunu Genel Tebliği",
      "Yeniden Değerleme Oranı"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:vuk-yeniden-degerleme-orani",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-tmgd",
    "order": 6,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "Tehlikeli Madde Güvenlik Danışmanlığı Hakkında Tebliğ",
    "category": "dangerous_goods_transport",
    "priority": "high",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "main_use": "Tehlikeli madde taşımacılığı yapan işletmelerde TMGD yükümlülüğü",
    "source_url": null,
    "doc_number": "teblig-tmgd",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": "https://www.resmigazete.gov.tr/eskiler/2014/05/20140522.htm",
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": null,
    "first_publication_date": "2014-05-22",
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": [
      "Tehlikeli Madde Güvenlik Danışmanlığı Hakkında Tebliğde Değişiklik"
    ],
    "resolver_title_contains": null,
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:tmgd",
    "sync_interval_days": 14,
    "admin_sync_only": true
  },
  {
    "id": "teblig-bekra-guvenlik-raporu",
    "order": 7,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "Büyük Endüstriyel Kazalarla İlgili Güvenlik Raporu Tebliği",
    "category": "major_accident_prevention",
    "priority": "sectoral_critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "main_use": "BEKRA kapsamındaki üst seviyeli kuruluşlarda güvenlik raporu içeriği",
    "source_url": null,
    "doc_number": "teblig-bekra-guvenlik-raporu",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Büyük Endüstriyel Kazalarla İlgili Güvenlik Raporu Tebliği"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:bekra-guvenlik-raporu",
    "sync_interval_days": 14,
    "admin_sync_only": true
  },
  {
    "id": "teblig-bekra-dahili-acil-durum-plani",
    "order": 8,
    "doc_type": "communique",
    "source_type": "communique",
    "title": "Büyük Endüstriyel Kazalarla İlgili Dahili Acil Durum Planı Tebliği",
    "category": "major_accident_prevention",
    "priority": "sectoral_critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı / AFAD",
    "main_use": "BEKRA kapsamındaki kuruluşlarda dahili acil durum planı içeriği",
    "source_url": null,
    "doc_number": "teblig-bekra-dahili-acil-durum-plani",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Büyük Endüstriyel Kazalarla İlgili Dahili Acil Durum Planı Tebliği"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:bekra-dahili-acil-durum-plani",
    "sync_interval_days": 14,
    "admin_sync_only": true
  },
  {
    "id": "teblig-kimyasallar-sds-guvenlik-bilgi-formu",
    "order": 9,
    "doc_type": "communique",
    "source_type": "communique_or_regulation_related",
    "title": "Güvenlik Bilgi Formları ve kimyasal güvenlik bilgi formu yükümlülüklerine ilişkin tebliğ/değişiklik kaynakları",
    "category": "chemical_sds",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "main_use": "SDS/GBF, zararlı madde ve karışımlar, kimyasal risk değerlendirmesi",
    "source_url": null,
    "doc_number": "teblig-kimyasallar-sds-guvenlik-bilgi-formu",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Güvenlik Bilgi Formları",
      "Zararlı Maddeler ve Karışımlara İlişkin Güvenlik Bilgi Formları",
      "Kimyasalların Kaydı, Değerlendirilmesi, İzni ve Kısıtlanması",
      "Maddelerin ve Karışımların Sınıflandırılması, Etiketlenmesi ve Ambalajlanması"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:chemical-sds",
    "sync_interval_days": 14,
    "admin_sync_only": true
  },
  {
    "id": "teblig-makina-uyumlastirilmis-standartlar",
    "order": 10,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Makina Emniyeti Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "machinery_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "main_use": "Makine emniyeti, CE, uygunluk değerlendirmesi ve teknik standart bağlantısı",
    "source_url": null,
    "doc_number": "teblig-makina-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Makina Emniyeti Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar",
      "Makine Emniyeti Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:makina-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-kkd-uyumlastirilmis-standartlar",
    "order": 11,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Kişisel Koruyucu Donanım Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "ppe_product_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "main_use": "KKD uygunluk, CE, standart ve ürün güvenliği bağlantısı",
    "source_url": null,
    "doc_number": "teblig-kkd-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Kişisel Koruyucu Donanım Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar",
      "Kişisel Koruyucu Donanım Yönetmeliği Kapsamında Uyumlaştırılmış Ulusal Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:kkd-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-basincili-ekipman-uyumlastirilmis-standartlar",
    "order": 12,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Basınçlı Ekipmanlar Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "pressure_equipment_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "main_use": "Basınçlı kap, kazan, tank, kompresör ve basınçlı sistem uygunluğu",
    "source_url": null,
    "doc_number": "teblig-basincili-ekipman-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Basınçlı Ekipmanlar Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:basincili-ekipman-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-atex-uyumlastirilmis-standartlar",
    "order": 13,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Muhtemel Patlayıcı Ortamda Kullanılan Teçhizat ve Koruyucu Sistemler ile İlgili Yönetmelik Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "atex_equipment_safety",
    "priority": "sectoral_critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "main_use": "ATEX ekipman, patlayıcı ortam, CE ve uygunluk değerlendirmesi",
    "source_url": null,
    "doc_number": "teblig-atex-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Muhtemel Patlayıcı Ortamda Kullanılan Teçhizat",
      "Koruyucu Sistemler",
      "Uyumlaştırılmış Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:atex-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  },
  {
    "id": "teblig-yapi-malzemeleri-uyumlastirilmis-standartlar",
    "order": 14,
    "doc_type": "communique",
    "source_type": "harmonized_standards_communique",
    "title": "Yapı Malzemeleri Yönetmeliği Kapsamında Uyumlaştırılmış Standartlara Dair Tebliğler",
    "category": "construction_product_safety",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "main_use": "Yapı malzemeleri, şantiye ve yapı güvenliğiyle bağlantılı ürün standardı kaynakları",
    "source_url": null,
    "doc_number": "teblig-yapi-malzemeleri-uyumlastirilmis-standartlar",
    "mevzuat_tur": 9,
    "mevzuat_tertip": 5,
    "mevzuat_lookup_url": "https://www.mevzuat.gov.tr/",
    "resmi_gazete_issue_url": null,
    "resmi_gazete_issue_no": null,
    "resmi_gazete_lookup_url": "https://www.resmigazete.gov.tr/",
    "first_publication_date": null,
    "official_lookup_url": null,
    "official_url": null,
    "change_resolver_title_contains": null,
    "resolver_title_contains": [
      "Yapı Malzemeleri Yönetmeliği Kapsamında Uyumlaştırılmış Standartlar"
    ],
    "expected_document_pattern": null,
    "rag_key_prefix": "communique:yapi-malzemeleri-uyumlastirilmis-standartlar",
    "sync_interval_days": 30,
    "admin_sync_only": true
  }
]$catalog$::jsonb) AS r(
  id text,
  "order" int,
  doc_type text,
  source_type text,
  title text,
  category text,
  priority text,
  authority text,
  main_use text,
  source_url text,
  doc_number text,
  mevzuat_tur int,
  mevzuat_tertip int,
  mevzuat_lookup_url text,
  resmi_gazete_issue_url text,
  resmi_gazete_issue_no text,
  resmi_gazete_lookup_url text,
  first_publication_date text,
  official_lookup_url text,
  official_url text,
  change_resolver_title_contains jsonb,
  resolver_title_contains jsonb,
  expected_document_pattern jsonb,
  rag_key_prefix text,
  sync_interval_days int,
  admin_sync_only boolean
)
ON CONFLICT (title, doc_number) WHERE doc_number IS NOT NULL DO UPDATE SET
  source_url = EXCLUDED.source_url,
  catalog_metadata = EXCLUDED.catalog_metadata,
  corpus_scope = EXCLUDED.corpus_scope,
  jurisdiction_code = EXCLUDED.jurisdiction_code,
  is_active = EXCLUDED.is_active,
  doc_type = EXCLUDED.doc_type,
  updated_at = now();

COMMIT;
