BEGIN;

-- Merge legacy regulation rows (old doc_number / PDF-only seeds) by title.
WITH catalog AS (
  SELECT
    r.doc_number::text AS doc_number,
    r.title::text AS title,
    nullif(r.canonical_url, '')::text AS source_url,
    jsonb_strip_nulls(jsonb_build_object(
      'catalog_id', r.id,
      'catalog_order', r."order",
      'category', r.category,
      'priority', r.priority,
      'authority', r.authority,
      'canonical_url', nullif(r.canonical_url, ''),
      'official_lookup_url', r.official_lookup_url,
      'rg_issue_url', nullif(r.rg_issue_url, ''),
      'sync_mode', r.sync_mode,
      'mevzuat_no', r.mevzuat_no,
      'canonical_resolved', (r.canonical_url IS NOT NULL AND r.canonical_url <> ''),
      'admin_sync_only', true,
      'sync_interval_days', 7,
      'last_status', CASE
        WHEN r.canonical_url IS NOT NULL AND r.canonical_url <> '' THEN 'resolved'
        ELSE 'pending'
      END
    )) AS catalog_metadata
  FROM jsonb_to_recordset($catalog$[
  {
    "id": "reg-isg-hizmetleri",
    "order": 1,
    "title": "İş Sağlığı ve Güvenliği Hizmetleri Yönetmeliği",
    "category": "core_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=16924&MevzuatTur=7&MevzuatTertip=5",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2012/12/20121229.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "16924",
    "doc_number": "16924"
  },
  {
    "id": "reg-risk-degerlendirmesi",
    "order": 2,
    "title": "İş Sağlığı ve Güvenliği Risk Değerlendirmesi Yönetmeliği",
    "category": "core_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=16925&MevzuatTur=7&MevzuatTertip=5",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2012/12/20121229.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "16925",
    "doc_number": "16925"
  },
  {
    "id": "reg-isg-kurullari",
    "order": 3,
    "title": "İş Sağlığı ve Güvenliği Kurulları Hakkında Yönetmelik",
    "category": "core_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/01/20130118.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isg-kurullari"
  },
  {
    "id": "reg-is-guvenligi-uzmanlari",
    "order": 4,
    "title": "İş Güvenliği Uzmanlarının Görev, Yetki, Sorumluluk ve Eğitimleri Hakkında Yönetmelik",
    "category": "core_isg_professionals",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2012/12/20121229.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-is-guvenligi-uzmanlari"
  },
  {
    "id": "reg-isyeri-hekimi-dsp",
    "order": 5,
    "title": "İşyeri Hekimi ve Diğer Sağlık Personelinin Görev, Yetki, Sorumluluk ve Eğitimleri Hakkında Yönetmelik",
    "category": "core_isg_professionals",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130720.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isyeri-hekimi-dsp"
  },
  {
    "id": "reg-calisan-isg-egitimleri",
    "order": 6,
    "title": "Çalışanların İş Sağlığı ve Güvenliği Eğitimlerinin Usul ve Esasları Hakkında Yönetmelik",
    "category": "core_isg_training",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/05/20130515.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-calisan-isg-egitimleri"
  },
  {
    "id": "reg-acil-durumlar",
    "order": 7,
    "title": "İşyerlerinde Acil Durumlar Hakkında Yönetmelik",
    "category": "core_isg_emergency",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/06/20130618.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-acil-durumlar"
  },
  {
    "id": "reg-isin-durdurulmasi",
    "order": 8,
    "title": "İşyerlerinde İşin Durdurulmasına Dair Yönetmelik",
    "category": "core_isg_enforcement",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/03/20130330.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isin-durdurulmasi"
  },
  {
    "id": "reg-isg-hizmetlerinin-desteklenmesi",
    "order": 9,
    "title": "İş Sağlığı ve Güvenliği Hizmetlerinin Desteklenmesi Hakkında Yönetmelik",
    "category": "core_isg_support",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/12/20131224.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isg-hizmetlerinin-desteklenmesi"
  },
  {
    "id": "reg-is-ekipmanlari",
    "order": 10,
    "title": "İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği",
    "category": "technical_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=18318&MevzuatTur=7&MevzuatTertip=5",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/04/20130425.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "18318",
    "doc_number": "18318"
  },
  {
    "id": "reg-isyeri-bina-eklentileri",
    "order": 11,
    "title": "İşyeri Bina ve Eklentilerinde Alınacak Sağlık ve Güvenlik Önlemlerine İlişkin Yönetmelik",
    "category": "technical_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130717.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isyeri-bina-eklentileri"
  },
  {
    "id": "reg-kkd-isyerinde-kullanim",
    "order": 12,
    "title": "Kişisel Koruyucu Donanımların İşyerlerinde Kullanılması Hakkında Yönetmelik",
    "category": "technical_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130702.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kkd-isyerinde-kullanim"
  },
  {
    "id": "reg-saglik-guvenlik-isaretleri",
    "order": 13,
    "title": "Sağlık ve Güvenlik İşaretleri Yönetmeliği",
    "category": "technical_isg",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/09/20130911.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-saglik-guvenlik-isaretleri"
  },
  {
    "id": "reg-ekranli-araclar",
    "order": 14,
    "title": "Ekranlı Araçlarla Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "ergonomics",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/04/20130416.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-ekranli-araclar"
  },
  {
    "id": "reg-elle-tasima",
    "order": 15,
    "title": "Elle Taşıma İşleri Yönetmeliği",
    "category": "ergonomics",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130724.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-elle-tasima"
  },
  {
    "id": "reg-gurultu",
    "order": 16,
    "title": "Çalışanların Gürültü ile İlgili Risklerden Korunmalarına Dair Yönetmelik",
    "category": "physical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=18647&MevzuatTur=7&MevzuatTertip=5",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130728.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "18647",
    "doc_number": "18647"
  },
  {
    "id": "reg-titresim",
    "order": 17,
    "title": "Çalışanların Titreşimle İlgili Risklerden Korunmalarına Dair Yönetmelik",
    "category": "physical_agents",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130822.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-titresim"
  },
  {
    "id": "reg-tozla-mucadele",
    "order": 18,
    "title": "Tozla Mücadele Yönetmeliği",
    "category": "physical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/11/20131105.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tozla-mucadele"
  },
  {
    "id": "reg-kimyasal-maddeler",
    "order": 19,
    "title": "Kimyasal Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "chemical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130812.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kimyasal-maddeler"
  },
  {
    "id": "reg-kanserojen-mutajen",
    "order": 20,
    "title": "Kanserojen veya Mutajen Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "chemical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130806.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kanserojen-mutajen"
  },
  {
    "id": "reg-biyolojik-etkenler",
    "order": 21,
    "title": "Biyolojik Etkenlere Maruziyet Risklerinin Önlenmesi Hakkında Yönetmelik",
    "category": "biological_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/06/20130615.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-biyolojik-etkenler"
  },
  {
    "id": "reg-asbest",
    "order": 22,
    "title": "Asbestle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "chemical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/01/20130125.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-asbest"
  },
  {
    "id": "reg-patlayici-ortamlar-calisan",
    "order": 23,
    "title": "Patlayıcı Ortamların Tehlikelerinden Çalışanların Korunması Hakkında Yönetmelik",
    "category": "explosive_atmospheres",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/04/20130430.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-patlayici-ortamlar-calisan"
  },
  {
    "id": "reg-is-hijyeni-lab",
    "order": 24,
    "title": "İş Hijyeni Ölçüm, Test ve Analiz Laboratuvarları Hakkında Yönetmelik",
    "category": "industrial_hygiene",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2023/01/20230127.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-is-hijyeni-lab"
  },
  {
    "id": "reg-yapi-islerinde-isg",
    "order": 25,
    "title": "Yapı İşlerinde İş Sağlığı ve Güvenliği Yönetmeliği",
    "category": "sector_construction",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/10/20131005.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-yapi-islerinde-isg"
  },
  {
    "id": "reg-maden-isyerlerinde-isg",
    "order": 26,
    "title": "Maden İşyerlerinde İş Sağlığı ve Güvenliği Yönetmeliği",
    "category": "sector_mining",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/09/20130919.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-maden-isyerlerinde-isg"
  },
  {
    "id": "reg-balikci-gemileri",
    "order": 27,
    "title": "Balıkçı Gemilerinde Yapılan Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "sector_marine",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130820.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-balikci-gemileri"
  },
  {
    "id": "reg-gecici-belirli-sureli-isler",
    "order": 28,
    "title": "Geçici veya Belirli Süreli İşlerde İş Sağlığı ve Güvenliği Hakkında Yönetmelik",
    "category": "temporary_work",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130823.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-gecici-belirli-sureli-isler"
  },
  {
    "id": "reg-tehlikeli-islerde-mesleki-egitim",
    "order": 29,
    "title": "Tehlikeli ve Çok Tehlikeli Sınıfta Yer Alan İşlerde Çalıştırılacakların Mesleki Eğitimlerine Dair Yönetmelik",
    "category": "vocational_training",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130713.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tehlikeli-islerde-mesleki-egitim"
  },
  {
    "id": "reg-cocuk-genc-isciler",
    "order": 30,
    "title": "Çocuk ve Genç İşçilerin Çalıştırılma Usul ve Esasları Hakkında Yönetmelik",
    "category": "protected_groups",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-cocuk-genc-isciler"
  },
  {
    "id": "reg-gebe-emziren-calisanlar",
    "order": 31,
    "title": "Gebe veya Emziren Kadınların Çalıştırılma Şartlarıyla Emzirme Odaları ve Çocuk Bakım Yurtlarına Dair Yönetmelik",
    "category": "protected_groups",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130816.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-gebe-emziren-calisanlar"
  },
  {
    "id": "reg-kadin-gece-postalari",
    "order": 32,
    "title": "Kadın Çalışanların Gece Postalarında Çalıştırılma Koşulları Hakkında Yönetmelik",
    "category": "protected_groups",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130724.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kadin-gece-postalari"
  },
  {
    "id": "reg-postalar-halinde-calisma",
    "order": 33,
    "title": "Postalar Halinde İşçi Çalıştırılarak Yürütülen İşlerde Çalışmalara İlişkin Özel Usul ve Esaslar Hakkında Yönetmelik",
    "category": "working_time",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040407.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-postalar-halinde-calisma"
  },
  {
    "id": "reg-calisma-sureleri",
    "order": 34,
    "title": "İş Kanununa İlişkin Çalışma Süreleri Yönetmeliği",
    "category": "working_time",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-calisma-sureleri"
  },
  {
    "id": "reg-fazla-calisma",
    "order": 35,
    "title": "Fazla Çalışma ve Fazla Sürelerle Çalışma Yönetmeliği",
    "category": "working_time",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-fazla-calisma"
  },
  {
    "id": "reg-haftalik-is-gunlerine-bolunemeyen-calisma",
    "order": 36,
    "title": "Haftalık İş Günlerine Bölünemeyen Çalışma Süreleri Yönetmeliği",
    "category": "working_time",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-haftalik-is-gunlerine-bolunemeyen-calisma"
  },
  {
    "id": "reg-hazirlama-tamamlama-temizleme",
    "order": 37,
    "title": "Hazırlama, Tamamlama ve Temizleme İşleri Yönetmeliği",
    "category": "working_time",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040428.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-hazirlama-tamamlama-temizleme"
  },
  {
    "id": "reg-alt-isverenlik",
    "order": 38,
    "title": "Alt İşverenlik Yönetmeliği",
    "category": "subcontracting",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2008/09/20080927.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-alt-isverenlik"
  },
  {
    "id": "reg-uzaktan-calisma",
    "order": 39,
    "title": "Uzaktan Çalışma Yönetmeliği",
    "category": "remote_work",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2021/03/20210310.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-uzaktan-calisma"
  },
  {
    "id": "reg-sosyal-sigorta-islemleri",
    "order": 40,
    "title": "Sosyal Sigorta İşlemleri Yönetmeliği",
    "category": "sgk_accident_disease",
    "priority": "critical",
    "authority": "Sosyal Güvenlik Kurumu",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-sosyal-sigorta-islemleri"
  },
  {
    "id": "reg-ilkyardim",
    "order": 41,
    "title": "İlkyardım Yönetmeliği",
    "category": "health_emergency",
    "priority": "critical",
    "authority": "Sağlık Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2015/07/20150729.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-ilkyardim"
  },
  {
    "id": "reg-hijyen-egitimi",
    "order": 42,
    "title": "Hijyen Eğitimi Yönetmeliği",
    "category": "health_hygiene",
    "priority": "high",
    "authority": "Sağlık Bakanlığı / ilgili kurumlar",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130705.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-hijyen-egitimi"
  },
  {
    "id": "reg-kisisel-saglik-verileri",
    "order": 43,
    "title": "Kişisel Sağlık Verileri Hakkında Yönetmelik",
    "category": "health_data_privacy",
    "priority": "high",
    "authority": "Sağlık Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2019/06/20190621.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kisisel-saglik-verileri"
  },
  {
    "id": "reg-binalarin-yangindan-korunmasi",
    "order": 44,
    "title": "Binaların Yangından Korunması Hakkında Yönetmelik",
    "category": "fire_safety",
    "priority": "critical",
    "authority": "Cumhurbaşkanlığı / ilgili idareler",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2007/12/20071219.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-binalarin-yangindan-korunmasi"
  },
  {
    "id": "reg-isyeri-acma-calisma-ruhsati",
    "order": 45,
    "title": "İşyeri Açma ve Çalışma Ruhsatlarına İlişkin Yönetmelik",
    "category": "workplace_license",
    "priority": "critical",
    "authority": "İçişleri Bakanlığı / yerel idareler",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2005/08/20050810.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isyeri-acma-calisma-ruhsati"
  },
  {
    "id": "reg-yapi-denetimi-uygulama",
    "order": 46,
    "title": "Yapı Denetimi Uygulama Yönetmeliği",
    "category": "construction_safety",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2008/02/20080205.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-yapi-denetimi-uygulama"
  },
  {
    "id": "reg-planli-alanlar-imar",
    "order": 47,
    "title": "Planlı Alanlar İmar Yönetmeliği",
    "category": "construction_safety",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2017/07/20170703.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-planli-alanlar-imar"
  },
  {
    "id": "reg-santiye-sefleri",
    "order": 48,
    "title": "Şantiye Şefleri Hakkında Yönetmelik",
    "category": "construction_safety",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-santiye-sefleri"
  },
  {
    "id": "reg-elektrik-ic-tesisleri",
    "order": 49,
    "title": "Elektrik İç Tesisleri Yönetmeliği",
    "category": "electrical_safety",
    "priority": "critical",
    "authority": "Enerji ve Tabii Kaynaklar Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/arsiv/18565.pdf",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-elektrik-ic-tesisleri"
  },
  {
    "id": "reg-elektrik-kuvvetli-akim",
    "order": 50,
    "title": "Elektrik Kuvvetli Akım Tesisleri Yönetmeliği",
    "category": "electrical_safety",
    "priority": "critical",
    "authority": "Enerji ve Tabii Kaynaklar Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/arsiv/24246.pdf",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-elektrik-kuvvetli-akim"
  },
  {
    "id": "reg-elektrik-topraklama",
    "order": 51,
    "title": "Elektrik Tesislerinde Topraklamalar Yönetmeliği",
    "category": "electrical_safety",
    "priority": "critical",
    "authority": "Enerji ve Tabii Kaynaklar Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/arsiv/24500.pdf",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-elektrik-topraklama"
  },
  {
    "id": "reg-asansor",
    "order": 52,
    "title": "Asansör Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-asansor"
  },
  {
    "id": "reg-asansor-bakim-periyodik-kontrol",
    "order": 53,
    "title": "Asansör İşletme, Bakım ve Periyodik Kontrol Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-asansor-bakim-periyodik-kontrol"
  },
  {
    "id": "reg-makina-emniyeti",
    "order": 54,
    "title": "Makina Emniyeti Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-makina-emniyeti"
  },
  {
    "id": "reg-basincili-ekipmanlar",
    "order": 55,
    "title": "Basınçlı Ekipmanlar Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-basincili-ekipmanlar"
  },
  {
    "id": "reg-basit-basincili-kaplar",
    "order": 56,
    "title": "Basit Basınçlı Kaplar Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-basit-basincili-kaplar"
  },
  {
    "id": "reg-tasinabilir-basincili-ekipmanlar",
    "order": 57,
    "title": "Taşınabilir Basınçlı Ekipmanlar Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "medium",
    "authority": "Ulaştırma ve Altyapı Bakanlığı / Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tasinabilir-basincili-ekipmanlar"
  },
  {
    "id": "reg-atex-ekipman",
    "order": 58,
    "title": "Muhtemel Patlayıcı Ortamda Kullanılan Teçhizat ve Koruyucu Sistemler ile İlgili Yönetmelik",
    "category": "explosive_atmospheres",
    "priority": "critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-atex-ekipman"
  },
  {
    "id": "reg-kkd-urun",
    "order": 59,
    "title": "Kişisel Koruyucu Donanım Yönetmeliği",
    "category": "ppe_product_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kkd-urun"
  },
  {
    "id": "reg-yapi-malzemeleri",
    "order": 60,
    "title": "Yapı Malzemeleri Yönetmeliği",
    "category": "construction_product_safety",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-yapi-malzemeleri"
  },
  {
    "id": "reg-bekta-bekra",
    "order": 61,
    "title": "Büyük Endüstriyel Kazaların Önlenmesi ve Etkilerinin Azaltılması Hakkında Yönetmelik",
    "category": "major_accident_prevention",
    "priority": "critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı / AFAD",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2019/03/20190302.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-bekta-bekra"
  },
  {
    "id": "reg-kkdik",
    "order": 62,
    "title": "Kimyasalların Kaydı, Değerlendirilmesi, İzni ve Kısıtlanması Hakkında Yönetmelik",
    "category": "chemical_regulation",
    "priority": "critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2017/06/20170623.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kkdik"
  },
  {
    "id": "reg-sea",
    "order": 63,
    "title": "Maddelerin ve Karışımların Sınıflandırılması, Etiketlenmesi ve Ambalajlanması Hakkında Yönetmelik",
    "category": "chemical_regulation",
    "priority": "critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/12/20131211.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-sea"
  },
  {
    "id": "reg-guvenlik-bilgi-formlari",
    "order": 64,
    "title": "Zararlı Maddeler ve Karışımlara İlişkin Güvenlik Bilgi Formları Hakkında Yönetmelik",
    "category": "chemical_regulation",
    "priority": "critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2014/12/20141213.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-guvenlik-bilgi-formlari"
  },
  {
    "id": "reg-atik-yonetimi",
    "order": 65,
    "title": "Atık Yönetimi Yönetmeliği",
    "category": "environment_waste",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2015/04/20150402.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-atik-yonetimi"
  },
  {
    "id": "reg-tibbi-atik",
    "order": 66,
    "title": "Tıbbi Atıkların Kontrolü Yönetmeliği",
    "category": "environment_waste",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2017/01/20170125.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tibbi-atik"
  },
  {
    "id": "reg-ced",
    "order": 67,
    "title": "Çevresel Etki Değerlendirmesi Yönetmeliği",
    "category": "environment_permit",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2022/07/20220729.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-ced"
  },
  {
    "id": "reg-cevre-izin-lisans",
    "order": 68,
    "title": "Çevre İzin ve Lisans Yönetmeliği",
    "category": "environment_permit",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2014/09/20140910.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-cevre-izin-lisans"
  },
  {
    "id": "reg-tehlikeli-madde-karayolu",
    "order": 69,
    "title": "Tehlikeli Maddelerin Karayoluyla Taşınması Hakkında Yönetmelik",
    "category": "dangerous_goods_transport",
    "priority": "critical",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tehlikeli-madde-karayolu"
  },
  {
    "id": "reg-tehlikeli-madde-demiryolu",
    "order": 70,
    "title": "Tehlikeli Maddelerin Demiryoluyla Taşınması Hakkında Yönetmelik",
    "category": "dangerous_goods_transport",
    "priority": "medium",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tehlikeli-madde-demiryolu"
  },
  {
    "id": "reg-tehlikeli-madde-denizyolu",
    "order": 71,
    "title": "Tehlikeli Maddelerin Denizyoluyla Taşınması Hakkında Yönetmelik",
    "category": "dangerous_goods_transport",
    "priority": "medium",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tehlikeli-madde-denizyolu"
  },
  {
    "id": "reg-karayolu-tasima",
    "order": 72,
    "title": "Karayolu Taşıma Yönetmeliği",
    "category": "transport_safety",
    "priority": "medium",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2018/01/20180108.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-karayolu-tasima"
  },
  {
    "id": "reg-radyasyon-guvenligi",
    "order": 73,
    "title": "Radyasyon Güvenliği Yönetmeliği",
    "category": "radiation_safety",
    "priority": "sectoral",
    "authority": "Nükleer Düzenleme Kurumu",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-radyasyon-guvenligi"
  },
  {
    "id": "reg-askeri-isyerleri-denetim",
    "order": 74,
    "title": "Askerî İşyerleri ile Yurt Güvenliği İçin Gerekli Maddeler Üretilen İşyerlerinin Denetimi, Teftişi ve Bu İşyerlerinde İşin Durdurulması Hakkında Yönetmelik",
    "category": "special_workplaces",
    "priority": "sectoral",
    "authority": "Millî Savunma Bakanlığı / Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/anasayfa/MevzuatFihristDetayIframe?MevzuatNo=18727&MevzuatTertip=5&MevzuatTur=7",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130816.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "18727",
    "doc_number": "18727"
  }
]$catalog$::jsonb) AS r(
    id text,
    "order" int,
    title text,
    category text,
    priority text,
    authority text,
    canonical_url text,
    official_lookup_url text,
    rg_issue_url text,
    sync_mode text,
    mevzuat_no text,
    doc_number text
  )
)
UPDATE public.legal_documents ld
SET
  doc_number = c.doc_number,
  source_url = c.source_url,
  catalog_metadata = c.catalog_metadata,
  corpus_scope = 'official',
  jurisdiction_code = 'TR',
  is_active = true,
  doc_type = 'regulation',
  updated_at = now()
FROM catalog c
WHERE ld.doc_type = 'regulation'
  AND ld.title = c.title;

INSERT INTO public.legal_documents (
  doc_type,
  doc_number,
  title,
  source_url,
  corpus_scope,
  jurisdiction_code,
  is_active,
  catalog_metadata
)
SELECT
  'regulation'::text,
  r.doc_number::text,
  r.title::text,
  nullif(r.canonical_url, '')::text,
  'official'::text,
  'TR'::text,
  true,
  jsonb_strip_nulls(jsonb_build_object(
    'catalog_id', r.id,
    'catalog_order', r."order",
    'category', r.category,
    'priority', r.priority,
    'authority', r.authority,
    'canonical_url', nullif(r.canonical_url, ''),
    'official_lookup_url', r.official_lookup_url,
    'rg_issue_url', nullif(r.rg_issue_url, ''),
    'sync_mode', r.sync_mode,
    'mevzuat_no', r.mevzuat_no,
    'canonical_resolved', (r.canonical_url IS NOT NULL AND r.canonical_url <> ''),
    'admin_sync_only', true,
    'sync_interval_days', 7,
    'last_status', CASE
      WHEN r.canonical_url IS NOT NULL AND r.canonical_url <> '' THEN 'resolved'
      ELSE 'pending'
    END
  ))
FROM jsonb_to_recordset($catalog$[
  {
    "id": "reg-isg-hizmetleri",
    "order": 1,
    "title": "İş Sağlığı ve Güvenliği Hizmetleri Yönetmeliği",
    "category": "core_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=16924&MevzuatTur=7&MevzuatTertip=5",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2012/12/20121229.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "16924",
    "doc_number": "16924"
  },
  {
    "id": "reg-risk-degerlendirmesi",
    "order": 2,
    "title": "İş Sağlığı ve Güvenliği Risk Değerlendirmesi Yönetmeliği",
    "category": "core_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=16925&MevzuatTur=7&MevzuatTertip=5",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2012/12/20121229.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "16925",
    "doc_number": "16925"
  },
  {
    "id": "reg-isg-kurullari",
    "order": 3,
    "title": "İş Sağlığı ve Güvenliği Kurulları Hakkında Yönetmelik",
    "category": "core_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/01/20130118.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isg-kurullari"
  },
  {
    "id": "reg-is-guvenligi-uzmanlari",
    "order": 4,
    "title": "İş Güvenliği Uzmanlarının Görev, Yetki, Sorumluluk ve Eğitimleri Hakkında Yönetmelik",
    "category": "core_isg_professionals",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2012/12/20121229.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-is-guvenligi-uzmanlari"
  },
  {
    "id": "reg-isyeri-hekimi-dsp",
    "order": 5,
    "title": "İşyeri Hekimi ve Diğer Sağlık Personelinin Görev, Yetki, Sorumluluk ve Eğitimleri Hakkında Yönetmelik",
    "category": "core_isg_professionals",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130720.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isyeri-hekimi-dsp"
  },
  {
    "id": "reg-calisan-isg-egitimleri",
    "order": 6,
    "title": "Çalışanların İş Sağlığı ve Güvenliği Eğitimlerinin Usul ve Esasları Hakkında Yönetmelik",
    "category": "core_isg_training",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/05/20130515.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-calisan-isg-egitimleri"
  },
  {
    "id": "reg-acil-durumlar",
    "order": 7,
    "title": "İşyerlerinde Acil Durumlar Hakkında Yönetmelik",
    "category": "core_isg_emergency",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/06/20130618.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-acil-durumlar"
  },
  {
    "id": "reg-isin-durdurulmasi",
    "order": 8,
    "title": "İşyerlerinde İşin Durdurulmasına Dair Yönetmelik",
    "category": "core_isg_enforcement",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/03/20130330.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isin-durdurulmasi"
  },
  {
    "id": "reg-isg-hizmetlerinin-desteklenmesi",
    "order": 9,
    "title": "İş Sağlığı ve Güvenliği Hizmetlerinin Desteklenmesi Hakkında Yönetmelik",
    "category": "core_isg_support",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/12/20131224.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isg-hizmetlerinin-desteklenmesi"
  },
  {
    "id": "reg-is-ekipmanlari",
    "order": 10,
    "title": "İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği",
    "category": "technical_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=18318&MevzuatTur=7&MevzuatTertip=5",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/04/20130425.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "18318",
    "doc_number": "18318"
  },
  {
    "id": "reg-isyeri-bina-eklentileri",
    "order": 11,
    "title": "İşyeri Bina ve Eklentilerinde Alınacak Sağlık ve Güvenlik Önlemlerine İlişkin Yönetmelik",
    "category": "technical_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130717.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isyeri-bina-eklentileri"
  },
  {
    "id": "reg-kkd-isyerinde-kullanim",
    "order": 12,
    "title": "Kişisel Koruyucu Donanımların İşyerlerinde Kullanılması Hakkında Yönetmelik",
    "category": "technical_isg",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130702.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kkd-isyerinde-kullanim"
  },
  {
    "id": "reg-saglik-guvenlik-isaretleri",
    "order": 13,
    "title": "Sağlık ve Güvenlik İşaretleri Yönetmeliği",
    "category": "technical_isg",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/09/20130911.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-saglik-guvenlik-isaretleri"
  },
  {
    "id": "reg-ekranli-araclar",
    "order": 14,
    "title": "Ekranlı Araçlarla Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "ergonomics",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/04/20130416.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-ekranli-araclar"
  },
  {
    "id": "reg-elle-tasima",
    "order": 15,
    "title": "Elle Taşıma İşleri Yönetmeliği",
    "category": "ergonomics",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130724.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-elle-tasima"
  },
  {
    "id": "reg-gurultu",
    "order": 16,
    "title": "Çalışanların Gürültü ile İlgili Risklerden Korunmalarına Dair Yönetmelik",
    "category": "physical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=18647&MevzuatTur=7&MevzuatTertip=5",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130728.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "18647",
    "doc_number": "18647"
  },
  {
    "id": "reg-titresim",
    "order": 17,
    "title": "Çalışanların Titreşimle İlgili Risklerden Korunmalarına Dair Yönetmelik",
    "category": "physical_agents",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130822.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-titresim"
  },
  {
    "id": "reg-tozla-mucadele",
    "order": 18,
    "title": "Tozla Mücadele Yönetmeliği",
    "category": "physical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/11/20131105.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tozla-mucadele"
  },
  {
    "id": "reg-kimyasal-maddeler",
    "order": 19,
    "title": "Kimyasal Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "chemical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130812.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kimyasal-maddeler"
  },
  {
    "id": "reg-kanserojen-mutajen",
    "order": 20,
    "title": "Kanserojen veya Mutajen Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "chemical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130806.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kanserojen-mutajen"
  },
  {
    "id": "reg-biyolojik-etkenler",
    "order": 21,
    "title": "Biyolojik Etkenlere Maruziyet Risklerinin Önlenmesi Hakkında Yönetmelik",
    "category": "biological_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/06/20130615.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-biyolojik-etkenler"
  },
  {
    "id": "reg-asbest",
    "order": 22,
    "title": "Asbestle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "chemical_agents",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/01/20130125.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-asbest"
  },
  {
    "id": "reg-patlayici-ortamlar-calisan",
    "order": 23,
    "title": "Patlayıcı Ortamların Tehlikelerinden Çalışanların Korunması Hakkında Yönetmelik",
    "category": "explosive_atmospheres",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/04/20130430.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-patlayici-ortamlar-calisan"
  },
  {
    "id": "reg-is-hijyeni-lab",
    "order": 24,
    "title": "İş Hijyeni Ölçüm, Test ve Analiz Laboratuvarları Hakkında Yönetmelik",
    "category": "industrial_hygiene",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2023/01/20230127.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-is-hijyeni-lab"
  },
  {
    "id": "reg-yapi-islerinde-isg",
    "order": 25,
    "title": "Yapı İşlerinde İş Sağlığı ve Güvenliği Yönetmeliği",
    "category": "sector_construction",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/10/20131005.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-yapi-islerinde-isg"
  },
  {
    "id": "reg-maden-isyerlerinde-isg",
    "order": 26,
    "title": "Maden İşyerlerinde İş Sağlığı ve Güvenliği Yönetmeliği",
    "category": "sector_mining",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/09/20130919.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-maden-isyerlerinde-isg"
  },
  {
    "id": "reg-balikci-gemileri",
    "order": 27,
    "title": "Balıkçı Gemilerinde Yapılan Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "category": "sector_marine",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130820.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-balikci-gemileri"
  },
  {
    "id": "reg-gecici-belirli-sureli-isler",
    "order": 28,
    "title": "Geçici veya Belirli Süreli İşlerde İş Sağlığı ve Güvenliği Hakkında Yönetmelik",
    "category": "temporary_work",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130823.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-gecici-belirli-sureli-isler"
  },
  {
    "id": "reg-tehlikeli-islerde-mesleki-egitim",
    "order": 29,
    "title": "Tehlikeli ve Çok Tehlikeli Sınıfta Yer Alan İşlerde Çalıştırılacakların Mesleki Eğitimlerine Dair Yönetmelik",
    "category": "vocational_training",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130713.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tehlikeli-islerde-mesleki-egitim"
  },
  {
    "id": "reg-cocuk-genc-isciler",
    "order": 30,
    "title": "Çocuk ve Genç İşçilerin Çalıştırılma Usul ve Esasları Hakkında Yönetmelik",
    "category": "protected_groups",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-cocuk-genc-isciler"
  },
  {
    "id": "reg-gebe-emziren-calisanlar",
    "order": 31,
    "title": "Gebe veya Emziren Kadınların Çalıştırılma Şartlarıyla Emzirme Odaları ve Çocuk Bakım Yurtlarına Dair Yönetmelik",
    "category": "protected_groups",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130816.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-gebe-emziren-calisanlar"
  },
  {
    "id": "reg-kadin-gece-postalari",
    "order": 32,
    "title": "Kadın Çalışanların Gece Postalarında Çalıştırılma Koşulları Hakkında Yönetmelik",
    "category": "protected_groups",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130724.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kadin-gece-postalari"
  },
  {
    "id": "reg-postalar-halinde-calisma",
    "order": 33,
    "title": "Postalar Halinde İşçi Çalıştırılarak Yürütülen İşlerde Çalışmalara İlişkin Özel Usul ve Esaslar Hakkında Yönetmelik",
    "category": "working_time",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040407.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-postalar-halinde-calisma"
  },
  {
    "id": "reg-calisma-sureleri",
    "order": 34,
    "title": "İş Kanununa İlişkin Çalışma Süreleri Yönetmeliği",
    "category": "working_time",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-calisma-sureleri"
  },
  {
    "id": "reg-fazla-calisma",
    "order": 35,
    "title": "Fazla Çalışma ve Fazla Sürelerle Çalışma Yönetmeliği",
    "category": "working_time",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-fazla-calisma"
  },
  {
    "id": "reg-haftalik-is-gunlerine-bolunemeyen-calisma",
    "order": 36,
    "title": "Haftalık İş Günlerine Bölünemeyen Çalışma Süreleri Yönetmeliği",
    "category": "working_time",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040406.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-haftalik-is-gunlerine-bolunemeyen-calisma"
  },
  {
    "id": "reg-hazirlama-tamamlama-temizleme",
    "order": 37,
    "title": "Hazırlama, Tamamlama ve Temizleme İşleri Yönetmeliği",
    "category": "working_time",
    "priority": "medium",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2004/04/20040428.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-hazirlama-tamamlama-temizleme"
  },
  {
    "id": "reg-alt-isverenlik",
    "order": 38,
    "title": "Alt İşverenlik Yönetmeliği",
    "category": "subcontracting",
    "priority": "critical",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2008/09/20080927.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-alt-isverenlik"
  },
  {
    "id": "reg-uzaktan-calisma",
    "order": 39,
    "title": "Uzaktan Çalışma Yönetmeliği",
    "category": "remote_work",
    "priority": "high",
    "authority": "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2021/03/20210310.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-uzaktan-calisma"
  },
  {
    "id": "reg-sosyal-sigorta-islemleri",
    "order": 40,
    "title": "Sosyal Sigorta İşlemleri Yönetmeliği",
    "category": "sgk_accident_disease",
    "priority": "critical",
    "authority": "Sosyal Güvenlik Kurumu",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-sosyal-sigorta-islemleri"
  },
  {
    "id": "reg-ilkyardim",
    "order": 41,
    "title": "İlkyardım Yönetmeliği",
    "category": "health_emergency",
    "priority": "critical",
    "authority": "Sağlık Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2015/07/20150729.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-ilkyardim"
  },
  {
    "id": "reg-hijyen-egitimi",
    "order": 42,
    "title": "Hijyen Eğitimi Yönetmeliği",
    "category": "health_hygiene",
    "priority": "high",
    "authority": "Sağlık Bakanlığı / ilgili kurumlar",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/07/20130705.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-hijyen-egitimi"
  },
  {
    "id": "reg-kisisel-saglik-verileri",
    "order": 43,
    "title": "Kişisel Sağlık Verileri Hakkında Yönetmelik",
    "category": "health_data_privacy",
    "priority": "high",
    "authority": "Sağlık Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2019/06/20190621.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kisisel-saglik-verileri"
  },
  {
    "id": "reg-binalarin-yangindan-korunmasi",
    "order": 44,
    "title": "Binaların Yangından Korunması Hakkında Yönetmelik",
    "category": "fire_safety",
    "priority": "critical",
    "authority": "Cumhurbaşkanlığı / ilgili idareler",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2007/12/20071219.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-binalarin-yangindan-korunmasi"
  },
  {
    "id": "reg-isyeri-acma-calisma-ruhsati",
    "order": 45,
    "title": "İşyeri Açma ve Çalışma Ruhsatlarına İlişkin Yönetmelik",
    "category": "workplace_license",
    "priority": "critical",
    "authority": "İçişleri Bakanlığı / yerel idareler",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2005/08/20050810.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-isyeri-acma-calisma-ruhsati"
  },
  {
    "id": "reg-yapi-denetimi-uygulama",
    "order": 46,
    "title": "Yapı Denetimi Uygulama Yönetmeliği",
    "category": "construction_safety",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2008/02/20080205.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-yapi-denetimi-uygulama"
  },
  {
    "id": "reg-planli-alanlar-imar",
    "order": 47,
    "title": "Planlı Alanlar İmar Yönetmeliği",
    "category": "construction_safety",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2017/07/20170703.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-planli-alanlar-imar"
  },
  {
    "id": "reg-santiye-sefleri",
    "order": 48,
    "title": "Şantiye Şefleri Hakkında Yönetmelik",
    "category": "construction_safety",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-santiye-sefleri"
  },
  {
    "id": "reg-elektrik-ic-tesisleri",
    "order": 49,
    "title": "Elektrik İç Tesisleri Yönetmeliği",
    "category": "electrical_safety",
    "priority": "critical",
    "authority": "Enerji ve Tabii Kaynaklar Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/arsiv/18565.pdf",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-elektrik-ic-tesisleri"
  },
  {
    "id": "reg-elektrik-kuvvetli-akim",
    "order": 50,
    "title": "Elektrik Kuvvetli Akım Tesisleri Yönetmeliği",
    "category": "electrical_safety",
    "priority": "critical",
    "authority": "Enerji ve Tabii Kaynaklar Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/arsiv/24246.pdf",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-elektrik-kuvvetli-akim"
  },
  {
    "id": "reg-elektrik-topraklama",
    "order": 51,
    "title": "Elektrik Tesislerinde Topraklamalar Yönetmeliği",
    "category": "electrical_safety",
    "priority": "critical",
    "authority": "Enerji ve Tabii Kaynaklar Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/arsiv/24500.pdf",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-elektrik-topraklama"
  },
  {
    "id": "reg-asansor",
    "order": 52,
    "title": "Asansör Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-asansor"
  },
  {
    "id": "reg-asansor-bakim-periyodik-kontrol",
    "order": 53,
    "title": "Asansör İşletme, Bakım ve Periyodik Kontrol Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-asansor-bakim-periyodik-kontrol"
  },
  {
    "id": "reg-makina-emniyeti",
    "order": 54,
    "title": "Makina Emniyeti Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-makina-emniyeti"
  },
  {
    "id": "reg-basincili-ekipmanlar",
    "order": 55,
    "title": "Basınçlı Ekipmanlar Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-basincili-ekipmanlar"
  },
  {
    "id": "reg-basit-basincili-kaplar",
    "order": 56,
    "title": "Basit Basınçlı Kaplar Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-basit-basincili-kaplar"
  },
  {
    "id": "reg-tasinabilir-basincili-ekipmanlar",
    "order": 57,
    "title": "Taşınabilir Basınçlı Ekipmanlar Yönetmeliği",
    "category": "machinery_product_safety",
    "priority": "medium",
    "authority": "Ulaştırma ve Altyapı Bakanlığı / Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tasinabilir-basincili-ekipmanlar"
  },
  {
    "id": "reg-atex-ekipman",
    "order": 58,
    "title": "Muhtemel Patlayıcı Ortamda Kullanılan Teçhizat ve Koruyucu Sistemler ile İlgili Yönetmelik",
    "category": "explosive_atmospheres",
    "priority": "critical",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-atex-ekipman"
  },
  {
    "id": "reg-kkd-urun",
    "order": 59,
    "title": "Kişisel Koruyucu Donanım Yönetmeliği",
    "category": "ppe_product_safety",
    "priority": "high",
    "authority": "Sanayi ve Teknoloji Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kkd-urun"
  },
  {
    "id": "reg-yapi-malzemeleri",
    "order": 60,
    "title": "Yapı Malzemeleri Yönetmeliği",
    "category": "construction_product_safety",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-yapi-malzemeleri"
  },
  {
    "id": "reg-bekta-bekra",
    "order": 61,
    "title": "Büyük Endüstriyel Kazaların Önlenmesi ve Etkilerinin Azaltılması Hakkında Yönetmelik",
    "category": "major_accident_prevention",
    "priority": "critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı / AFAD",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2019/03/20190302.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-bekta-bekra"
  },
  {
    "id": "reg-kkdik",
    "order": 62,
    "title": "Kimyasalların Kaydı, Değerlendirilmesi, İzni ve Kısıtlanması Hakkında Yönetmelik",
    "category": "chemical_regulation",
    "priority": "critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2017/06/20170623.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-kkdik"
  },
  {
    "id": "reg-sea",
    "order": 63,
    "title": "Maddelerin ve Karışımların Sınıflandırılması, Etiketlenmesi ve Ambalajlanması Hakkında Yönetmelik",
    "category": "chemical_regulation",
    "priority": "critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/12/20131211.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-sea"
  },
  {
    "id": "reg-guvenlik-bilgi-formlari",
    "order": 64,
    "title": "Zararlı Maddeler ve Karışımlara İlişkin Güvenlik Bilgi Formları Hakkında Yönetmelik",
    "category": "chemical_regulation",
    "priority": "critical",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2014/12/20141213.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-guvenlik-bilgi-formlari"
  },
  {
    "id": "reg-atik-yonetimi",
    "order": 65,
    "title": "Atık Yönetimi Yönetmeliği",
    "category": "environment_waste",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2015/04/20150402.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-atik-yonetimi"
  },
  {
    "id": "reg-tibbi-atik",
    "order": 66,
    "title": "Tıbbi Atıkların Kontrolü Yönetmeliği",
    "category": "environment_waste",
    "priority": "high",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2017/01/20170125.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tibbi-atik"
  },
  {
    "id": "reg-ced",
    "order": 67,
    "title": "Çevresel Etki Değerlendirmesi Yönetmeliği",
    "category": "environment_permit",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2022/07/20220729.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-ced"
  },
  {
    "id": "reg-cevre-izin-lisans",
    "order": 68,
    "title": "Çevre İzin ve Lisans Yönetmeliği",
    "category": "environment_permit",
    "priority": "medium",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2014/09/20140910.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-cevre-izin-lisans"
  },
  {
    "id": "reg-tehlikeli-madde-karayolu",
    "order": 69,
    "title": "Tehlikeli Maddelerin Karayoluyla Taşınması Hakkında Yönetmelik",
    "category": "dangerous_goods_transport",
    "priority": "critical",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tehlikeli-madde-karayolu"
  },
  {
    "id": "reg-tehlikeli-madde-demiryolu",
    "order": 70,
    "title": "Tehlikeli Maddelerin Demiryoluyla Taşınması Hakkında Yönetmelik",
    "category": "dangerous_goods_transport",
    "priority": "medium",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tehlikeli-madde-demiryolu"
  },
  {
    "id": "reg-tehlikeli-madde-denizyolu",
    "order": 71,
    "title": "Tehlikeli Maddelerin Denizyoluyla Taşınması Hakkında Yönetmelik",
    "category": "dangerous_goods_transport",
    "priority": "medium",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-tehlikeli-madde-denizyolu"
  },
  {
    "id": "reg-karayolu-tasima",
    "order": 72,
    "title": "Karayolu Taşıma Yönetmeliği",
    "category": "transport_safety",
    "priority": "medium",
    "authority": "Ulaştırma ve Altyapı Bakanlığı",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2018/01/20180108.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-karayolu-tasima"
  },
  {
    "id": "reg-radyasyon-guvenligi",
    "order": 73,
    "title": "Radyasyon Güvenliği Yönetmeliği",
    "category": "radiation_safety",
    "priority": "sectoral",
    "authority": "Nükleer Düzenleme Kurumu",
    "canonical_url": null,
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": null,
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": null,
    "doc_number": "reg-radyasyon-guvenligi"
  },
  {
    "id": "reg-askeri-isyerleri-denetim",
    "order": 74,
    "title": "Askerî İşyerleri ile Yurt Güvenliği İçin Gerekli Maddeler Üretilen İşyerlerinin Denetimi, Teftişi ve Bu İşyerlerinde İşin Durdurulması Hakkında Yönetmelik",
    "category": "special_workplaces",
    "priority": "sectoral",
    "authority": "Millî Savunma Bakanlığı / Çalışma ve Sosyal Güvenlik Bakanlığı",
    "canonical_url": "https://www.mevzuat.gov.tr/anasayfa/MevzuatFihristDetayIframe?MevzuatNo=18727&MevzuatTertip=5&MevzuatTur=7",
    "official_lookup_url": "https://www.mevzuat.gov.tr/",
    "rg_issue_url": "https://www.resmigazete.gov.tr/eskiler/2013/08/20130816.htm",
    "sync_mode": "admin_only_weekly",
    "mevzuat_no": "18727",
    "doc_number": "18727"
  }
]$catalog$::jsonb) AS r(
  id text,
  "order" int,
  title text,
  category text,
  priority text,
  authority text,
  canonical_url text,
  official_lookup_url text,
  rg_issue_url text,
  sync_mode text,
  mevzuat_no text,
  doc_number text
)
ON CONFLICT (title, doc_number) WHERE doc_number IS NOT NULL DO UPDATE SET
  source_url = EXCLUDED.source_url,
  catalog_metadata = EXCLUDED.catalog_metadata,
  corpus_scope = EXCLUDED.corpus_scope,
  jurisdiction_code = EXCLUDED.jurisdiction_code,
  is_active = EXCLUDED.is_active,
  doc_type = EXCLUDED.doc_type,
  updated_at = now();

COMMIT;
